/**
 * ONE-SHOT WEBAUTHN CHALLENGES.
 *
 * A WebAuthn challenge is the whole anti-replay story: the authenticator
 * signs over it, and a challenge that verifies TWICE means a captured
 * assertion can be presented again. So a record here must be:
 *
 *   RANDOM      — generated by `@simplewebauthn/server` (CSPRNG), never by us.
 *   SINGLE-USE  — `take()` reads and destroys ATOMICALLY. Not `get` then
 *                 `delete`: two concurrent replays would both read before
 *                 either deleted, and both would verify.
 *   SHORT-LIVED — 5 minutes, enforced by the store's own TTL rather than a
 *                 timestamp comparison the reader could forget to make.
 *   BOUND       — to a purpose AND a subject, via the key (`reg:<userId>`,
 *                 `reg-required:<userId>`, `mfa:<userId>`,
 *                 `login:<challengeId>`). A registration challenge must not
 *                 be spendable at the login endpoint, and one user's
 *                 challenge must not be spendable by another.
 *
 *                 `reg` and `reg-required` are DELIBERATELY separate purposes
 *                 even though both end in a registration. `reg` is minted
 *                 behind a session AND a re-authentication (the password, or
 *                 the single-use post-sign-in grant — see
 *                 `passkey-enrollment-grant.ts`); `reg-required` is
 *                 minted on the unauthenticated forced-enrollment door, where
 *                 the only authorization is a partial `mfaToken`. Sharing one
 *                 key would let a challenge issued at the weaker door be
 *                 spent at the stronger one, or vice versa, and would also
 *                 let a ceremony started at one endpoint be finished at the
 *                 other.
 *
 *                 `enroll-grant` (2026-09-22) is not a challenge at all: it
 *                 is the namespace of the post-sign-in passkey offer's grant.
 *                 It lives behind the same key builder so that every
 *                 namespace this family uses stays visible in one line, and it
 *                 is spent with the same atomic read-and-delete
 *                 (`redisTakeOnce`) — there is exactly ONE copy of that
 *                 primitive.
 *
 * The record also carries the RESOLVED relying party. See `webauthn-config.ts`
 * — the `{ rpID, origin }` pair a ceremony is verified against must be the one
 * pinned when the options were issued, not a fresh read at verify time.
 *
 * ── WHY TWO BACKENDS, AND WHY NEVER BOTH AT ONCE ──────────────────────────
 * Redis is OPTIONAL in this product (CLAUDE.md: the API boots and serves with
 * no Redis at all), so a Redis-only store would make passkeys silently
 * unusable on such a deploy. The in-process map is the fallback.
 *
 * They are chosen per operation and NEVER mirrored. Writing a challenge to
 * both would destroy the single-use guarantee outright: a replay could spend
 * the Redis copy and then spend the memory copy. And a Redis error during
 * `take()` returns null (the caller 401s and the user retries) rather than
 * falling back to memory, because "Redis might have already consumed this"
 * is not a state in which we may accept a second presentation.
 *
 * The honest limitation, stated plainly: on the memory backend with more than
 * one replica, a ceremony only completes if both halves land on the same pod,
 * and single-use only holds within that pod. That is a degradation of an
 * optional-dependency deploy, not the designed posture — set `REDIS_URL`.
 */

import { Logger } from '@nestjs/common';

/** Five minutes. Long enough for a user to find their security key, short
 *  enough that a captured options response is not a standing credential. */
export const WEBAUTHN_CHALLENGE_TTL_MS = 5 * 60_000;

export interface WebAuthnChallengeRecord {
  /** The base64url challenge exactly as `generateXOptions` produced it. */
  challenge: string;
  /** Pinned at options time — see the header. */
  rpID: string;
  /** Pinned at options time — see the header. */
  origin: string;
  /**
   * The user this ceremony belongs to, or `null` for a DISCOVERABLE passwordless
   * login, where the user is not known until the authenticator names a
   * credential. Present for `reg:` and `mfa:` so a stored record can be
   * cross-checked against the principal that is spending it.
   */
  userId: string | null;
  issuedAt: number;
  /**
   * `reg:` only (2026-09-22) — WHAT re-authenticated the user who asked for
   * this registration ceremony: their password (Settings → My security), or
   * the single-use grant a real sign-in leaves behind (the post-sign-in
   * passkey offer, `passkey-enrollment-grant.ts`). Carried so the
   * `PASSKEY_REGISTERED` audit row can say which door the credential came
   * through. Absent on every other purpose and on any record written before
   * the field existed; readers treat absent as `'password'`, which was the
   * only door there was.
   */
  reauth?: WebAuthnRegistrationReauth;
}

/** How a `reg:` ceremony's requester re-proved who they are. */
export type WebAuthnRegistrationReauth = 'password' | 'enrollment-grant';

/** The contract both backends implement, and the only thing callers see. */
export interface WebAuthnChallengeStore {
  /** Store (or replace) the record at `key`. Last write wins. */
  put(
    key: string,
    record: WebAuthnChallengeRecord,
    ttlMs?: number,
  ): Promise<void>;
  /** Read AND destroy atomically. `null` when absent, expired or already spent. */
  take(key: string): Promise<WebAuthnChallengeRecord | null>;
}

/**
 * The slice of ioredis we use. Declared locally and cast at the call site —
 * the same pattern as `sports/beacon-capability.ts` and
 * `security/ingest-rate-limit.ts` — so this module has no ioredis import and
 * stays unit-testable with a plain object.
 */
export interface WebAuthnChallengeRedis {
  status?: string;
  set(key: string, value: string, mode: 'PX', ttlMs: number): Promise<unknown>;
  /** Redis 6.2+. Atomic read-and-delete — the single-use primitive. */
  getdel(key: string): Promise<string | null>;
  /** ioredis transaction builder — only used when the SERVER lacks GETDEL. */
  multi?: () => {
    get(key: string): unknown;
    del(key: string): unknown;
    exec(): Promise<Array<[Error | null, unknown]> | null>;
  };
}

/** `ERR unknown command 'GETDEL'` — a Redis server older than 6.2. */
function isUnknownCommand(err: unknown): boolean {
  return /unknown command/i.test(
    String((err as { message?: unknown })?.message ?? err ?? ''),
  );
}

const KEY_PREFIX = 'vos:webauthn:';

/**
 * Namespace a purpose-bound key.
 *
 * The union is closed on purpose: a caller cannot invent a purpose, so every
 * namespace in use is visible in this one line. `reg-required` (2026-09-21)
 * is the forced-enrollment registration door — see the header for why it is
 * not simply `reg`. `enroll-grant` (2026-09-22) is the post-sign-in passkey
 * offer's grant — see `passkey-enrollment-grant.ts`.
 */
export function challengeKey(
  purpose: 'reg' | 'reg-required' | 'mfa' | 'login' | 'enroll-grant',
  subject: string,
): string {
  return `${KEY_PREFIX}${purpose}:${subject}`;
}

/**
 * Is this Redis handle one a single-use record may be written to and taken
 * from? The ONE predicate for that question — `resolveChallengeStore` and the
 * enrollment-grant store both ask it, so the two can never disagree about
 * which backend a deploy is on.
 */
export function isUsableChallengeRedis(
  redis: WebAuthnChallengeRedis | null | undefined,
): redis is WebAuthnChallengeRedis {
  return (
    !!redis && redis.status === 'ready' && typeof redis.getdel === 'function'
  );
}

/**
 * THE single-use primitive: read a key and destroy it in one atomic step.
 *
 * Returns the raw stored string, or `null` when the key is absent, expired,
 * already spent — OR when Redis failed in a way that leaves us unable to tell
 * whether it was spent. That last case is deliberately indistinguishable from
 * "absent": the caller refuses, and never falls back to a second copy.
 *
 * Extracted (2026-09-22) from `RedisWebAuthnChallengeStore.take` without a
 * behavioural change, so the passkey-enrollment grant spends its records
 * through the SAME code rather than a second, drifting copy of it.
 */
export async function redisTakeOnce(
  redis: WebAuthnChallengeRedis,
  key: string,
): Promise<string | null> {
  try {
    // GETDEL is atomic: exactly one concurrent caller receives the value.
    const raw = await redis.getdel(key);
    return typeof raw === 'string' ? raw : null;
  } catch (err) {
    // GETDEL needs Redis >= 6.2. The client library always HAS the method,
    // so an older SERVER only shows up here, at runtime, as `unknown
    // command` — and with a bare `return null` every passkey ceremony in
    // that deployment would fail closed forever, looking exactly like "the
    // passkey wasn't accepted". (The lead could not read production's Redis
    // version without a tool that also prints secrets, so this does not get
    // to be an assumption.) MULTI/EXEC runs GET then DEL with nothing
    // interleaved, so the single-use guarantee is identical.
    if (isUnknownCommand(err) && typeof redis.multi === 'function') {
      try {
        const tx = redis.multi();
        tx.get(key);
        tx.del(key);
        const res = await tx.exec();
        const raw = res?.[0]?.[1];
        return typeof raw === 'string' ? raw : null;
      } catch {
        return null;
      }
    }
    // Any OTHER Redis error mid-take: we cannot tell whether the record was
    // consumed, so we refuse — never a fall-through to the memory map, which
    // would be a second, independently spendable copy.
    return null;
  }
}

function parseRecord(
  raw: string | null | undefined,
): WebAuthnChallengeRecord | null {
  if (typeof raw !== 'string' || !raw) return null;
  try {
    const parsed = JSON.parse(raw) as Partial<WebAuthnChallengeRecord>;
    if (
      !parsed ||
      typeof parsed.challenge !== 'string' ||
      !parsed.challenge ||
      typeof parsed.rpID !== 'string' ||
      !parsed.rpID ||
      typeof parsed.origin !== 'string' ||
      !parsed.origin
    ) {
      return null;
    }
    return {
      challenge: parsed.challenge,
      rpID: parsed.rpID,
      origin: parsed.origin,
      userId: typeof parsed.userId === 'string' ? parsed.userId : null,
      issuedAt: typeof parsed.issuedAt === 'number' ? parsed.issuedAt : 0,
      // Only the two values the union names survive a round-trip; anything
      // else is dropped and reads as the legacy "password".
      ...(parsed.reauth === 'password' || parsed.reauth === 'enrollment-grant'
        ? { reauth: parsed.reauth }
        : {}),
    };
  } catch {
    return null;
  }
}

/**
 * Per-process fallback. Bounded and self-pruning so a flood of options calls
 * cannot grow it without limit (same shape as the beacon replay map).
 */
const MEMORY_LIMIT = 10_000;

/**
 * The memory backend, for any single-use record. Generic since 2026-09-22 so
 * the passkey-enrollment grant spends its records through the SAME
 * delete-first logic the challenges use, rather than a second copy of it.
 */
export class MemoryOneShotStore<T> {
  private readonly entries = new Map<
    string,
    { record: T; expiresAt: number }
  >();

  async put(
    key: string,
    record: T,
    ttlMs: number = WEBAUTHN_CHALLENGE_TTL_MS,
  ): Promise<void> {
    const now = Date.now();
    this.prune(now);
    this.entries.set(key, { record, expiresAt: now + ttlMs });
  }

  async take(key: string): Promise<T | null> {
    const now = Date.now();
    const hit = this.entries.get(key);
    // Delete FIRST, unconditionally: a record that is read is spent, whether
    // or not the verification that follows succeeds. Leaving it in place on a
    // failed verify would give an attacker unlimited attempts against one
    // challenge.
    this.entries.delete(key);
    if (!hit) return null;
    if (hit.expiresAt <= now) return null;
    return hit.record;
  }

  /** Test seam — the map is per-instance, but a suite may want a clean slate. */
  clear(): void {
    this.entries.clear();
  }

  private prune(now: number): void {
    if (this.entries.size < MEMORY_LIMIT) return;
    for (const [key, entry] of this.entries) {
      if (entry.expiresAt <= now) this.entries.delete(key);
    }
    if (this.entries.size < MEMORY_LIMIT) return;
    // Still oversized after dropping expired rows — shed the oldest half
    // rather than growing without bound. Map preserves insertion order.
    let drop = Math.floor(this.entries.size / 2);
    for (const key of this.entries.keys()) {
      this.entries.delete(key);
      if (--drop <= 0) break;
    }
  }
}

export class MemoryWebAuthnChallengeStore
  extends MemoryOneShotStore<WebAuthnChallengeRecord>
  implements WebAuthnChallengeStore {}

export class RedisWebAuthnChallengeStore implements WebAuthnChallengeStore {
  constructor(private readonly redis: WebAuthnChallengeRedis) {}

  async put(
    key: string,
    record: WebAuthnChallengeRecord,
    ttlMs: number = WEBAUTHN_CHALLENGE_TTL_MS,
  ): Promise<void> {
    await this.redis.set(
      key,
      JSON.stringify(record),
      'PX',
      Math.max(1_000, Math.ceil(ttlMs)),
    );
  }

  async take(key: string): Promise<WebAuthnChallengeRecord | null> {
    // Atomic read-and-delete, with the old-server MULTI fallback and the
    // fail-closed rule — see `redisTakeOnce`.
    return parseRecord(await redisTakeOnce(this.redis, key));
  }
}

const sharedMemoryStore = new MemoryWebAuthnChallengeStore();
const logger = new Logger('WebAuthnChallengeStore');
let warnedMemoryFallback = false;

/**
 * Pick the backend for ONE operation. Both halves of a ceremony normally land
 * on the same one; if Redis drops out between them the verify simply fails
 * closed and the user retries.
 */
export function resolveChallengeStore(
  redis: WebAuthnChallengeRedis | null | undefined,
): WebAuthnChallengeStore {
  if (isUsableChallengeRedis(redis)) {
    return new RedisWebAuthnChallengeStore(redis);
  }
  if (!warnedMemoryFallback) {
    warnedMemoryFallback = true;
    logger.warn(
      'Redis is unavailable — passkey challenges are being held in process memory. ' +
        'Ceremonies still work, but with more than one replica a challenge is only ' +
        'single-use within the pod that issued it. Set REDIS_URL.',
    );
  }
  return sharedMemoryStore;
}

/** Test seam: let a suite observe the warning again. */
export function __resetChallengeStoreWarningForTests(): void {
  warnedMemoryFallback = false;
  sharedMemoryStore.clear();
}
