-- 2026-10-05 — EMAILED SIGN-IN CODE (the second step when the account's passkey is on another device).
--
-- WHY. The owner's only passkey lives on his Mac; on his iPhone the second step asked for it, iOS
-- could not find it and showed its cross-device QR code, and there was no other way through. A
-- 6-digit code mailed to the account is now one of the "sign in another way on this device" options
-- — only AFTER the password was proven (a row is created by presenting the partial mfaToken that
-- /auth/login mints after a correct password), 10-minute expiry, single use, at most 5 attempts.
-- Nothing usable is stored: the page's handle as a SHA-256, the code as an HMAC keyed by a server
-- secret (see apps/api/src/auth/mfa-email-code.ts).
--
-- ADDITIVE AND NON-DESTRUCTIVE: one brand-new table, three indexes, one foreign key. Nothing existing
-- is altered. The FK only REFERENCES "users": adding it takes SHARE ROW EXCLUSIVE on "users", which
-- does not block reads, and the new table is empty so validation is instant. lock_timeout keeps even
-- that brief lock from queueing behind a long transaction on "users" (every sign-in reads it).
--
-- IDEMPOTENT because the dev flow is `pnpm db:push`: IF NOT EXISTS on the table and every index, and
-- the foreign key behind a pg_constraint guard, so a database that already took this shape applies
-- the file as a no-op.
--
-- DDL generated by Prisma (`migrate diff --from-schema-datamodel <9a84e65d> --to-schema-datamodel
-- <this commit> --script`) and then made idempotent — the column list is unchanged from its output.

SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS "mfa_email_codes" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "challenge_hash" TEXT NOT NULL,
    "code_hash" TEXT NOT NULL,
    "remember_me" BOOLEAN NOT NULL DEFAULT false,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "ip_hash" TEXT,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "used_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mfa_email_codes_pkey" PRIMARY KEY ("id")
);

-- The page's handle → its row (single lookup on verify).
CREATE UNIQUE INDEX IF NOT EXISTS "mfa_email_codes_challenge_hash_key"
  ON "mfa_email_codes"("challenge_hash");

-- Per-account send limit + "expire the older codes when a new one is sent".
CREATE INDEX IF NOT EXISTS "mfa_email_codes_user_id_created_at_idx"
  ON "mfa_email_codes"("user_id", "created_at");

-- Per-IP send limit.
CREATE INDEX IF NOT EXISTS "mfa_email_codes_ip_hash_created_at_idx"
  ON "mfa_email_codes"("ip_hash", "created_at");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'mfa_email_codes_user_id_fkey'
  ) THEN
    ALTER TABLE "mfa_email_codes"
      ADD CONSTRAINT "mfa_email_codes_user_id_fkey"
      FOREIGN KEY ("user_id") REFERENCES "users"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
