-- 2026-09-23 — AI board credits: board packs bought through Stripe, and each month's included
-- board allowance (apps/api/src/ai/ai-board-credits.ts).
--
-- WHY. The AI Designer on our key is now sold in BOARDS (one per candidate drawn, one per "edit with
-- words" refine): the plan includes max(10, 5 x paired screens) per organisation per UTC month, and
-- a one-off Stripe payment adds a pack of boards for 12 months. Usage is COUNTED from the existing
-- ai_usage_events ledger by feature; these two tables hold the only other state:
--   * ai_credit_purchases — one row per paid Checkout Session (UNIQUE stripe_session_id, so a
--     re-delivered webhook can never credit twice);
--   * ai_board_months — per organisation per month, that month's included allowance as a high-water
--     mark, because a pack is consumed only by boards drawn beyond a month's included allowance and a
--     past month cannot be recomputed from today's screen count.
--
-- ADDITIVE AND NON-DESTRUCTIVE: two brand-new tables and their indexes. Nothing existing is altered
-- or referenced (no foreign keys — a paid purchase is a financial record that must outlive any
-- tenant cleanup), so no lock is taken on any existing table. lock_timeout is kept anyway, per the
-- house rule, so a surprise lock fails fast instead of queueing.
--
-- IDEMPOTENT because the dev flow is `pnpm db:push`: IF NOT EXISTS on both tables and every index,
-- so a database that already took this shape applies the file as a no-op.
--
-- DDL generated by Prisma (`migrate diff --from-schema-datamodel <master> --to-schema-datamodel
-- <this commit> --script`) and then made idempotent — the column lists are unchanged from its output.

SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS "ai_credit_purchases" (
    "id" TEXT NOT NULL,
    "org_tenant_id" TEXT NOT NULL,
    "stripe_session_id" TEXT NOT NULL,
    "pack" TEXT NOT NULL,
    "boards" INTEGER NOT NULL,
    "usd_micros" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ai_credit_purchases_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ai_board_months" (
    "org_tenant_id" TEXT NOT NULL,
    "month" TEXT NOT NULL,
    "included_boards" INTEGER NOT NULL,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_board_months_pkey" PRIMARY KEY ("org_tenant_id","month")
);

-- One purchase per Checkout Session, ever — the webhook's idempotency on the SESSION (the
-- processed_stripe_events ledger already dedups the EVENT id).
CREATE UNIQUE INDEX IF NOT EXISTS "ai_credit_purchases_stripe_session_id_key"
  ON "ai_credit_purchases"("stripe_session_id");

-- An organisation's live packs (every board check).
CREATE INDEX IF NOT EXISTS "ai_credit_purchases_org_tenant_id_expires_at_idx"
  ON "ai_credit_purchases"("org_tenant_id", "expires_at");

-- This month's pack revenue across every organisation (the super-admin margin view).
CREATE INDEX IF NOT EXISTS "ai_credit_purchases_created_at_idx"
  ON "ai_credit_purchases"("created_at");
