// AUTO-GENERATED catalog of the self-contained signage / HS templates.
// Regenerate by re-running the extraction in scripts after adding
// templates. Backs the "Industry Signage Template" widget picker tile
// and its template dropdown in the builder Properties panel.

export interface SignageTemplate {
  /** matches the system-presets.ts preset id */
  id: string;
  /** display name, emoji stripped */
  name: string;
  /** industry / level group, for the dropdown optgroups */
  group: string;
  /** /public path served same-origin */
  url: string;
}

export const SIGNAGE_TEMPLATES: SignageTemplate[] = [
  { id: "preset-hs-ath-gameday", name: "Athletics — Game Day Hub", group: "High School", url: "/templates/hs/ath-gameday.html" },
  { id: "preset-hs-ath-standings", name: "Athletics — Standings & AOTW", group: "High School", url: "/templates/hs/ath-standings.html" },
  { id: "preset-hs-caf-today", name: "Cafeteria — Today + Tomorrow", group: "High School", url: "/templates/hs/caf-today.html" },
  { id: "preset-hs-caf-counter", name: "Cafeteria — Counter Plate", group: "High School", url: "/templates/hs/caf-counter.html" },
  { id: "preset-hs-caf-market", name: "Cafeteria — Food-Hall Market", group: "High School", url: "/templates/hs/caf-market.html" },
  { id: "preset-hs-class-nownext", name: "Classroom — Now / Next Agenda", group: "High School", url: "/templates/hs/class-nownext.html" },
  { id: "preset-hs-class-subday", name: "Classroom — Substitute Self-Running Plan", group: "High School", url: "/templates/hs/class-subday.html" },
  { id: "preset-hs-hall-bulletin", name: "Hallway — Corkboard Bulletin", group: "High School", url: "/templates/hs/hall-bulletin.html" },
  { id: "preset-hs-hall-wayfinder", name: "Hallway — Wayfinder Departures", group: "High School", url: "/templates/hs/hall-wayfinder.html" },
  { id: "preset-sig-bar-01", name: "Bar · Tap List", group: "Bar", url: "/templates/signage/bar/01-tap-list-flagship.html" },
  { id: "preset-sig-bar-02", name: "Bar · Cocktails", group: "Bar", url: "/templates/signage/bar/02-cocktail-menu.html" },
  { id: "preset-sig-bar-03", name: "Bar · Bottle List", group: "Bar", url: "/templates/signage/bar/03-bottle-list.html" },
  { id: "preset-sig-bar-04", name: "Bar · Happy Hour", group: "Bar", url: "/templates/signage/bar/04-happy-hour.html" },
  { id: "preset-sig-bar-05", name: "Bar · Now Pouring", group: "Bar", url: "/templates/signage/bar/05-now-pouring.html" },
  { id: "preset-sig-bar-06", name: "Bar · Tonight", group: "Bar", url: "/templates/signage/bar/06-tonight-live.html" },
  { id: "preset-sig-bar-07", name: "Bar · Bottle Service", group: "Bar", url: "/templates/signage/bar/07-bottle-service.html" },
  { id: "preset-sig-bar-08", name: "Bar · Game Day", group: "Bar", url: "/templates/signage/bar/08-game-day.html" },
  { id: "preset-sig-bar-09", name: "Bar · Hours", group: "Bar", url: "/templates/signage/bar/09-hours-location.html" },
  { id: "preset-sig-bar-10", name: "Bar · Hiring", group: "Bar", url: "/templates/signage/bar/10-now-hiring.html" },
  { id: "preset-sig-corporate-01", name: "Corporate · Lobby", group: "Corporate", url: "/templates/signage/corporate/01-lobby-welcome-flagship.html" },
  { id: "preset-sig-corporate-02", name: "Corporate · Conference", group: "Corporate", url: "/templates/signage/corporate/02-conference-room.html" },
  { id: "preset-sig-corporate-03", name: "Corporate · KPI Dashboard", group: "Corporate", url: "/templates/signage/corporate/03-kpi-dashboard.html" },
  { id: "preset-sig-corporate-04", name: "Corporate · New Hires", group: "Corporate", url: "/templates/signage/corporate/04-new-hires.html" },
  { id: "preset-sig-corporate-05", name: "Corporate · Floor Directory", group: "Corporate", url: "/templates/signage/corporate/05-floor-directory.html" },
  { id: "preset-sig-corporate-06", name: "Corporate · All Hands", group: "Corporate", url: "/templates/signage/corporate/06-all-hands.html" },
  { id: "preset-sig-corporate-07", name: "Corporate · Cafeteria", group: "Corporate", url: "/templates/signage/corporate/07-cafeteria.html" },
  { id: "preset-sig-corporate-08", name: "Corporate · Shuttle", group: "Corporate", url: "/templates/signage/corporate/08-shuttle-board.html" },
  { id: "preset-sig-corporate-09", name: "Corporate · Events", group: "Corporate", url: "/templates/signage/corporate/09-events-week.html" },
  { id: "preset-sig-corporate-10", name: "Corporate · Emergency", group: "Corporate", url: "/templates/signage/corporate/10-emergency-info.html" },
  { id: "preset-sig-fashion-01", name: "Fashion · Lookbook", group: "Fashion", url: "/templates/signage/fashion/01-lookbook-flagship.html" },
  { id: "preset-sig-fashion-02", name: "Fashion · Editorial", group: "Fashion", url: "/templates/signage/fashion/02-editorial.html" },
  { id: "preset-sig-fashion-03", name: "Fashion · Sale", group: "Fashion", url: "/templates/signage/fashion/03-sale.html" },
  { id: "preset-sig-fashion-04", name: "Fashion · New Arrivals", group: "Fashion", url: "/templates/signage/fashion/04-new-arrivals.html" },
  { id: "preset-sig-fashion-05", name: "Fashion · Event", group: "Fashion", url: "/templates/signage/fashion/05-event-trunkshow.html" },
  { id: "preset-sig-fashion-06", name: "Fashion · Fitting", group: "Fashion", url: "/templates/signage/fashion/06-fitting-room.html" },
  { id: "preset-sig-fashion-07", name: "Fashion · Window", group: "Fashion", url: "/templates/signage/fashion/07-shoppable-window.html" },
  { id: "preset-sig-fashion-08", name: "Fashion · Campaign", group: "Fashion", url: "/templates/signage/fashion/08-campaign.html" },
  { id: "preset-sig-fashion-09", name: "Fashion · Hours", group: "Fashion", url: "/templates/signage/fashion/09-hours-story.html" },
  { id: "preset-sig-fashion-10", name: "Fashion · Members", group: "Fashion", url: "/templates/signage/fashion/10-loyalty-member.html" },
  { id: "preset-sig-healthcare-01", name: "Healthcare · Waiting Room", group: "Healthcare", url: "/templates/signage/healthcare/01-waiting-room-flagship.html" },
  { id: "preset-sig-healthcare-02", name: "Healthcare · Physicians", group: "Healthcare", url: "/templates/signage/healthcare/02-physician-directory.html" },
  { id: "preset-sig-healthcare-03", name: "Healthcare · Now Serving", group: "Healthcare", url: "/templates/signage/healthcare/03-now-serving.html" },
  { id: "preset-sig-healthcare-04", name: "Healthcare · Vaccines", group: "Healthcare", url: "/templates/signage/healthcare/04-vaccine-clinic.html" },
  { id: "preset-sig-healthcare-05", name: "Healthcare · Hours", group: "Healthcare", url: "/templates/signage/healthcare/05-hours-closures.html" },
  { id: "preset-sig-healthcare-06", name: "Healthcare · Patient Education", group: "Healthcare", url: "/templates/signage/healthcare/06-patient-education.html" },
  { id: "preset-sig-healthcare-07", name: "Healthcare · MyChart", group: "Healthcare", url: "/templates/signage/healthcare/07-mychart-signup.html" },
  { id: "preset-sig-healthcare-08", name: "Healthcare · Pharmacy", group: "Healthcare", url: "/templates/signage/healthcare/08-pharmacy-pickup.html" },
  { id: "preset-sig-healthcare-09", name: "Healthcare · Clinical Trial", group: "Healthcare", url: "/templates/signage/healthcare/09-clinical-trial.html" },
  { id: "preset-sig-healthcare-10", name: "Healthcare · Thanks", group: "Healthcare", url: "/templates/signage/healthcare/10-thanks-leave.html" },
  { id: "preset-sig-hospitality-01", name: "Hospitality · Lobby · Welcome", group: "Hospitality", url: "/templates/signage/hospitality/01-lobby-welcome-flagship.html" },
  { id: "preset-sig-hospitality-02", name: "Hospitality · Concierge · Tonight in town", group: "Hospitality", url: "/templates/signage/hospitality/02-concierge-board.html" },
  { id: "preset-sig-hospitality-03", name: "Hospitality · Today's Events", group: "Hospitality", url: "/templates/signage/hospitality/03-events-board.html" },
  { id: "preset-sig-hospitality-04", name: "Hospitality · Pool · Spa · Today", group: "Hospitality", url: "/templates/signage/hospitality/04-pool-spa-day.html" },
  { id: "preset-sig-hospitality-05", name: "Hospitality · Dining Tonight", group: "Hospitality", url: "/templates/signage/hospitality/05-dining-tonight.html" },
  { id: "preset-sig-hospitality-06", name: "Hospitality · Wayfinder", group: "Hospitality", url: "/templates/signage/hospitality/06-wayfinder.html" },
  { id: "preset-sig-hospitality-07", name: "Hospitality · Group Welcome", group: "Hospitality", url: "/templates/signage/hospitality/07-group-welcome.html" },
  { id: "preset-sig-hospitality-08", name: "Hospitality · Check-in", group: "Hospitality", url: "/templates/signage/hospitality/08-checkin-status.html" },
  { id: "preset-sig-hospitality-09", name: "Hospitality · Outlook", group: "Hospitality", url: "/templates/signage/hospitality/09-outlook.html" },
  { id: "preset-sig-hospitality-10", name: "Hospitality · Brand Story", group: "Hospitality", url: "/templates/signage/hospitality/10-brand-story.html" },
  { id: "preset-sig-menus-pos-01", name: "Menu · Menu", group: "Menus & POS", url: "/templates/signage/menus-pos/01-fullservice-menu.html" },
  { id: "preset-sig-menus-pos-02", name: "Menu · Wine List", group: "Menus & POS", url: "/templates/signage/menus-pos/02-wine-list.html" },
  { id: "preset-sig-menus-pos-03", name: "Menu · Daily Specials", group: "Menus & POS", url: "/templates/signage/menus-pos/03-daily-special.html" },
  { id: "preset-sig-menus-pos-04", name: "Menu · Cocktails", group: "Menus & POS", url: "/templates/signage/menus-pos/04-cocktail-program.html" },
  { id: "preset-sig-menus-pos-05", name: "Menu · POS 86 Board", group: "Menus & POS", url: "/templates/signage/menus-pos/05-86-board.html" },
  { id: "preset-sig-menus-pos-06", name: "Menu · Brunch Menu", group: "Menus & POS", url: "/templates/signage/menus-pos/06-brunch.html" },
  { id: "preset-sig-menus-pos-07", name: "Menu · Prix Fixe", group: "Menus & POS", url: "/templates/signage/menus-pos/07-prix-fixe.html" },
  { id: "preset-sig-menus-pos-08", name: "Menu · Tasting Progress", group: "Menus & POS", url: "/templates/signage/menus-pos/08-tasting-progress.html" },
  { id: "preset-sig-menus-pos-09", name: "Menu · Reservations", group: "Menus & POS", url: "/templates/signage/menus-pos/09-reservations.html" },
  { id: "preset-sig-menus-pos-10", name: "Menu · Takeaway", group: "Menus & POS", url: "/templates/signage/menus-pos/10-takeaway-pickup.html" },
  { id: "preset-sig-qsr-01", name: "QSR · Drive-Thru · Menu Board", group: "QSR", url: "/templates/signage/qsr/01-drive-thru-flagship.html" },
  { id: "preset-sig-qsr-02", name: "QSR · Counter Menu", group: "QSR", url: "/templates/signage/qsr/02-counter-menu.html" },
  { id: "preset-sig-qsr-03", name: "QSR · Order Ready", group: "QSR", url: "/templates/signage/qsr/03-order-ready.html" },
  { id: "preset-sig-qsr-04", name: "QSR · LTO Promo", group: "QSR", url: "/templates/signage/qsr/04-lto-promo.html" },
  { id: "preset-sig-qsr-05", name: "QSR · Combos & Deals", group: "QSR", url: "/templates/signage/qsr/05-combos-deals.html" },
  { id: "preset-sig-qsr-06", name: "QSR · Beverages", group: "QSR", url: "/templates/signage/qsr/06-beverages.html" },
  { id: "preset-sig-qsr-07", name: "QSR · Mobile Pickup", group: "QSR", url: "/templates/signage/qsr/07-mobile-pickup.html" },
  { id: "preset-sig-qsr-08", name: "QSR · Rewards", group: "QSR", url: "/templates/signage/qsr/08-rewards.html" },
  { id: "preset-sig-qsr-09", name: "QSR · Hours", group: "QSR", url: "/templates/signage/qsr/09-hours-location.html" },
  { id: "preset-sig-qsr-10", name: "QSR · Now Hiring", group: "QSR", url: "/templates/signage/qsr/10-now-hiring.html" },
];
