'use client';

/**
 * LAZY WIDGET FAMILIES — the chunk map (P1-1, 2026-09-03).
 *
 * GENERATED SHAPE, HAND-OWNED FILE. Every export is a `lazyWidget` proxy for
 * one export of one widget module, and every module gets exactly ONE loader
 * constant, so N proxies from the same file share a single `import()`, a
 * single chunk and a single load state.
 *
 * ── WHAT THIS BUYS ───────────────────────────────────────────────────────
 * `WidgetRenderer.tsx` used to name all 427 of these symbols in static imports
 * across 159 modules, so the whole widget catalog compiled into ONE chunk that
 * every `WidgetPreview` surface (player, builder, gallery) downloaded whole —
 * 3.37 MB raw / ~690 KB gzip, for a screen that may only be showing a clock.
 * Behind these proxies the bundler emits one chunk per family and a screen
 * fetches only the families its manifest actually references.
 *
 * ── RULES ────────────────────────────────────────────────────────────────
 * • Add a widget the same way: one loader const per module, one
 *   `lazyWidget<ThemeWidgetProps>(loader, 'ExportName')` per component, and import the symbol
 *   into `WidgetRenderer.tsx` from THIS file. Never add a static import of a
 *   widget family back into `WidgetRenderer.tsx` — one static edge merges
 *   that family's chunk back into the renderer island for the whole fleet.
 * • HOOKS AND VALUE-POSITION EXPORTS DO NOT BELONG HERE. A proxy is a
 *   component: a hook behind one would break the rules of hooks, and a helper
 *   called in value position would be a function that renders nothing. Those
 *   stay statically imported in `WidgetRenderer.tsx` (`countdown-utils`,
 *   `scene-css`, `use-live-feed`, `fitness/use-gym-media`,
 *   `sports/GameStateContext`).
 * • Nothing on the EMERGENCY path may be listed here. The alert surface
 *   (`EmergencyOverlay`) is statically imported by `player/page.tsx` and
 *   renders outside the renderer island, so an alert never waits on a chunk
 *   (player rule 11).
 *
 * See `lazy-widget.tsx` for the proxy's loading + retry contract.
 */

import { lazyWidget, loadWidgetChunk, type WidgetChunkLoader } from './lazy-widget';
// The prop contract every themed/family widget in this app already speaks.
// Typing the proxies with it keeps `render:` registrations and JSX call sites
// assignable exactly as they were before the split.
import type { ThemeWidgetProps } from './themes/registry';

// NEW AUTOGENERATED IMPORTS
const loadThemesGymPe = () => import('./themes/gym-pe');
export const GymPEText = lazyWidget<ThemeWidgetProps>(loadThemesGymPe, 'GymPEText');
export const GymPEWeather = lazyWidget<ThemeWidgetProps>(loadThemesGymPe, 'GymPEWeather');
export const GymPEBellSchedule = lazyWidget<ThemeWidgetProps>(loadThemesGymPe, 'GymPEBellSchedule');
export const GymPEAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesGymPe, 'GymPEAnnouncement');
export const GymPETicker = lazyWidget<ThemeWidgetProps>(loadThemesGymPe, 'GymPETicker');

const loadThemesPrincipalsOffice = () => import('./themes/principals-office');
export const PrincipalsOfficeLogo = lazyWidget<ThemeWidgetProps>(loadThemesPrincipalsOffice, 'PrincipalsOfficeLogo');
export const PrincipalsOfficeText = lazyWidget<ThemeWidgetProps>(loadThemesPrincipalsOffice, 'PrincipalsOfficeText');
export const PrincipalsOfficeClock = lazyWidget<ThemeWidgetProps>(loadThemesPrincipalsOffice, 'PrincipalsOfficeClock');
export const PrincipalsOfficeAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesPrincipalsOffice, 'PrincipalsOfficeAnnouncement');
export const PrincipalsOfficeRichText = lazyWidget<ThemeWidgetProps>(loadThemesPrincipalsOffice, 'PrincipalsOfficeRichText');
export const PrincipalsOfficeTicker = lazyWidget<ThemeWidgetProps>(loadThemesPrincipalsOffice, 'PrincipalsOfficeTicker');

const loadThemesOfficeDashboard = () => import('./themes/office-dashboard');
export const OfficeDashboardLogo = lazyWidget<ThemeWidgetProps>(loadThemesOfficeDashboard, 'OfficeDashboardLogo');
export const OfficeDashboardText = lazyWidget<ThemeWidgetProps>(loadThemesOfficeDashboard, 'OfficeDashboardText');
export const OfficeDashboardClock = lazyWidget<ThemeWidgetProps>(loadThemesOfficeDashboard, 'OfficeDashboardClock');
export const OfficeDashboardAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesOfficeDashboard, 'OfficeDashboardAnnouncement');
export const OfficeDashboardStaff = lazyWidget<ThemeWidgetProps>(loadThemesOfficeDashboard, 'OfficeDashboardStaff');
export const OfficeDashboardCalendar = lazyWidget<ThemeWidgetProps>(loadThemesOfficeDashboard, 'OfficeDashboardCalendar');
export const OfficeDashboardTicker = lazyWidget<ThemeWidgetProps>(loadThemesOfficeDashboard, 'OfficeDashboardTicker');

// AUTOGENERATED IMPORTS
const loadThemesBackToSchool = () => import('./themes/back-to-school');
export const BackToSchoolText = lazyWidget<ThemeWidgetProps>(loadThemesBackToSchool, 'BackToSchoolText');
export const BackToSchoolClock = lazyWidget<ThemeWidgetProps>(loadThemesBackToSchool, 'BackToSchoolClock');
export const BackToSchoolAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesBackToSchool, 'BackToSchoolAnnouncement');
export const BackToSchoolCalendar = lazyWidget<ThemeWidgetProps>(loadThemesBackToSchool, 'BackToSchoolCalendar');
export const BackToSchoolStaff = lazyWidget<ThemeWidgetProps>(loadThemesBackToSchool, 'BackToSchoolStaff');
export const BackToSchoolCountdown = lazyWidget<ThemeWidgetProps>(loadThemesBackToSchool, 'BackToSchoolCountdown');
export const BackToSchoolLogo = lazyWidget<ThemeWidgetProps>(loadThemesBackToSchool, 'BackToSchoolLogo');
export const BackToSchoolTicker = lazyWidget<ThemeWidgetProps>(loadThemesBackToSchool, 'BackToSchoolTicker');
export const BackToSchoolWeather = lazyWidget<ThemeWidgetProps>(loadThemesBackToSchool, 'BackToSchoolWeather');
export const BackToSchoolImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesBackToSchool, 'BackToSchoolImageCarousel');

const loadThemesBusLoop = () => import('./themes/bus-loop');
export const BusLoopText = lazyWidget<ThemeWidgetProps>(loadThemesBusLoop, 'BusLoopText');
export const BusLoopClock = lazyWidget<ThemeWidgetProps>(loadThemesBusLoop, 'BusLoopClock');
export const BusLoopTicker = lazyWidget<ThemeWidgetProps>(loadThemesBusLoop, 'BusLoopTicker');
export const BusLoopWeather = lazyWidget<ThemeWidgetProps>(loadThemesBusLoop, 'BusLoopWeather');
export const BusLoopAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesBusLoop, 'BusLoopAnnouncement');
export const BusLoopCalendar = lazyWidget<ThemeWidgetProps>(loadThemesBusLoop, 'BusLoopCalendar');

const loadThemesDinerChalkboard = () => import('./themes/diner-chalkboard');
export const DinerChalkboardText = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardText');
export const DinerChalkboardClock = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardClock');
export const DinerChalkboardLunchMenu = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardLunchMenu');
export const DinerChalkboardAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardAnnouncement');
export const DinerChalkboardCountdown = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardCountdown');
export const DinerChalkboardTicker = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardTicker');
export const DinerChalkboardCalendar = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardCalendar');
export const DinerChalkboardStaff = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardStaff');
export const DinerChalkboardLogo = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardLogo');
export const DinerChalkboardWeather = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardWeather');
export const DinerChalkboardImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesDinerChalkboard, 'DinerChalkboardImageCarousel');

const loadThemesFinalChance = () => import('./themes/final-chance');
export const FinalChanceClock = lazyWidget<ThemeWidgetProps>(loadThemesFinalChance, 'FinalChanceClock');
export const FinalChanceWeather = lazyWidget<ThemeWidgetProps>(loadThemesFinalChance, 'FinalChanceWeather');
export const FinalChanceText = lazyWidget<ThemeWidgetProps>(loadThemesFinalChance, 'FinalChanceText');
export const FinalChanceLogo = lazyWidget<ThemeWidgetProps>(loadThemesFinalChance, 'FinalChanceLogo');
export const FinalChanceAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesFinalChance, 'FinalChanceAnnouncement');
export const FinalChanceCalendar = lazyWidget<ThemeWidgetProps>(loadThemesFinalChance, 'FinalChanceCalendar');
export const FinalChanceCountdown = lazyWidget<ThemeWidgetProps>(loadThemesFinalChance, 'FinalChanceCountdown');
export const FinalChanceStaff = lazyWidget<ThemeWidgetProps>(loadThemesFinalChance, 'FinalChanceStaff');
export const FinalChanceImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesFinalChance, 'FinalChanceImageCarousel');
export const FinalChanceTicker = lazyWidget<ThemeWidgetProps>(loadThemesFinalChance, 'FinalChanceTicker');

const loadThemesHighSchoolAthletics = () => import('./themes/high-school-athletics');
export const AthleticsLogo = lazyWidget<ThemeWidgetProps>(loadThemesHighSchoolAthletics, 'AthleticsLogo');
export const AthleticsCountdown = lazyWidget<ThemeWidgetProps>(loadThemesHighSchoolAthletics, 'AthleticsCountdown');
export const AthleticsAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesHighSchoolAthletics, 'AthleticsAnnouncement');
export const AthleticsText = lazyWidget<ThemeWidgetProps>(loadThemesHighSchoolAthletics, 'AthleticsText');
export const AthleticsTicker = lazyWidget<ThemeWidgetProps>(loadThemesHighSchoolAthletics, 'AthleticsTicker');

const loadThemesLibraryQuiet = () => import('./themes/library-quiet');
export const LibraryQuietText = lazyWidget<ThemeWidgetProps>(loadThemesLibraryQuiet, 'LibraryQuietText');
export const LibraryQuietClock = lazyWidget<ThemeWidgetProps>(loadThemesLibraryQuiet, 'LibraryQuietClock');
export const LibraryQuietImage = lazyWidget<ThemeWidgetProps>(loadThemesLibraryQuiet, 'LibraryQuietImage');
export const LibraryQuietRichText = lazyWidget<ThemeWidgetProps>(loadThemesLibraryQuiet, 'LibraryQuietRichText');
export const LibraryQuietLunch = lazyWidget<ThemeWidgetProps>(loadThemesLibraryQuiet, 'LibraryQuietLunch');
export const LibraryQuietTicker = lazyWidget<ThemeWidgetProps>(loadThemesLibraryQuiet, 'LibraryQuietTicker');

const loadThemesMiddleSchoolHall = () => import('./themes/middle-school-hall');
export const MSHallClock = lazyWidget<ThemeWidgetProps>(loadThemesMiddleSchoolHall, 'MSHallClock');
export const MSHallBellSchedule = lazyWidget<ThemeWidgetProps>(loadThemesMiddleSchoolHall, 'MSHallBellSchedule');
export const MSHallTicker = lazyWidget<ThemeWidgetProps>(loadThemesMiddleSchoolHall, 'MSHallTicker');
export const MSHallAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesMiddleSchoolHall, 'MSHallAnnouncement');
export const MSHallImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesMiddleSchoolHall, 'MSHallImageCarousel');
export const MSHallWeather = lazyWidget<ThemeWidgetProps>(loadThemesMiddleSchoolHall, 'MSHallWeather');
export const MSHallText = lazyWidget<ThemeWidgetProps>(loadThemesMiddleSchoolHall, 'MSHallText');
export const MSHallCountdown = lazyWidget<ThemeWidgetProps>(loadThemesMiddleSchoolHall, 'MSHallCountdown');
export const MSHallStaff = lazyWidget<ThemeWidgetProps>(loadThemesMiddleSchoolHall, 'MSHallStaff');
export const MSHallLogo = lazyWidget<ThemeWidgetProps>(loadThemesMiddleSchoolHall, 'MSHallLogo');

const loadThemesMusicArts = () => import('./themes/music-arts');
export const MusicArtsText = lazyWidget<ThemeWidgetProps>(loadThemesMusicArts, 'MusicArtsText');
export const MusicArtsCountdown = lazyWidget<ThemeWidgetProps>(loadThemesMusicArts, 'MusicArtsCountdown');
export const MusicArtsRichText = lazyWidget<ThemeWidgetProps>(loadThemesMusicArts, 'MusicArtsRichText');
export const MusicArtsSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesMusicArts, 'MusicArtsSpotlight');
export const MusicArtsTicker = lazyWidget<ThemeWidgetProps>(loadThemesMusicArts, 'MusicArtsTicker');

const loadThemesStemScience = () => import('./themes/stem-science');
export const StemScienceText = lazyWidget<ThemeWidgetProps>(loadThemesStemScience, 'StemScienceText');
export const StemScienceCountdown = lazyWidget<ThemeWidgetProps>(loadThemesStemScience, 'StemScienceCountdown');
export const StemScienceRichText = lazyWidget<ThemeWidgetProps>(loadThemesStemScience, 'StemScienceRichText');
export const StemScienceImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesStemScience, 'StemScienceImageCarousel');
export const StemScienceTicker = lazyWidget<ThemeWidgetProps>(loadThemesStemScience, 'StemScienceTicker');

const loadThemesSunshineAcademy = () => import('./themes/sunshine-academy');
export const SunshineAcademyClock = lazyWidget<ThemeWidgetProps>(loadThemesSunshineAcademy, 'SunshineAcademyClock');
export const SunshineAcademyWeather = lazyWidget<ThemeWidgetProps>(loadThemesSunshineAcademy, 'SunshineAcademyWeather');
export const SunshineAcademyCountdown = lazyWidget<ThemeWidgetProps>(loadThemesSunshineAcademy, 'SunshineAcademyCountdown');
export const SunshineAcademyText = lazyWidget<ThemeWidgetProps>(loadThemesSunshineAcademy, 'SunshineAcademyText');
export const SunshineAcademyAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesSunshineAcademy, 'SunshineAcademyAnnouncement');
export const SunshineAcademyTicker = lazyWidget<ThemeWidgetProps>(loadThemesSunshineAcademy, 'SunshineAcademyTicker');
export const SunshineAcademyCalendar = lazyWidget<ThemeWidgetProps>(loadThemesSunshineAcademy, 'SunshineAcademyCalendar');
export const SunshineAcademyStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesSunshineAcademy, 'SunshineAcademyStaffSpotlight');
export const SunshineAcademyImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesSunshineAcademy, 'SunshineAcademyImageCarousel');

// Two shape-based elementary themes ported from the design-lab mockups.
// Every widget is a real SVG shape (pennants, speech bubbles, stopwatches,
// medals, jerseys) — not a rectangle with a background color.
const loadThemesRainbowRibbon = () => import('./themes/rainbow-ribbon');
export const RainbowRibbonLogo = lazyWidget<ThemeWidgetProps>(loadThemesRainbowRibbon, 'RainbowRibbonLogo');
export const RainbowRibbonText = lazyWidget<ThemeWidgetProps>(loadThemesRainbowRibbon, 'RainbowRibbonText');
export const RainbowRibbonClock = lazyWidget<ThemeWidgetProps>(loadThemesRainbowRibbon, 'RainbowRibbonClock');
export const RainbowRibbonWeather = lazyWidget<ThemeWidgetProps>(loadThemesRainbowRibbon, 'RainbowRibbonWeather');
export const RainbowRibbonCountdown = lazyWidget<ThemeWidgetProps>(loadThemesRainbowRibbon, 'RainbowRibbonCountdown');
export const RainbowRibbonAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesRainbowRibbon, 'RainbowRibbonAnnouncement');
export const RainbowRibbonCalendar = lazyWidget<ThemeWidgetProps>(loadThemesRainbowRibbon, 'RainbowRibbonCalendar');
export const RainbowRibbonStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesRainbowRibbon, 'RainbowRibbonStaffSpotlight');
export const RainbowRibbonImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesRainbowRibbon, 'RainbowRibbonImageCarousel');
export const RainbowRibbonTicker = lazyWidget<ThemeWidgetProps>(loadThemesRainbowRibbon, 'RainbowRibbonTicker');

const loadThemesRainbowAnimated = () => import('./themes/rainbow-animated');
export const RainbowAnimatedLogo = lazyWidget<ThemeWidgetProps>(loadThemesRainbowAnimated, 'RainbowAnimatedLogo');
export const RainbowAnimatedTitle = lazyWidget<ThemeWidgetProps>(loadThemesRainbowAnimated, 'RainbowAnimatedTitle');
export const RainbowAnimatedClock = lazyWidget<ThemeWidgetProps>(loadThemesRainbowAnimated, 'RainbowAnimatedClock');
export const RainbowAnimatedWeather = lazyWidget<ThemeWidgetProps>(loadThemesRainbowAnimated, 'RainbowAnimatedWeather');
export const RainbowAnimatedCountdown = lazyWidget<ThemeWidgetProps>(loadThemesRainbowAnimated, 'RainbowAnimatedCountdown');
export const RainbowAnimatedAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesRainbowAnimated, 'RainbowAnimatedAnnouncement');
export const RainbowAnimatedStaff = lazyWidget<ThemeWidgetProps>(loadThemesRainbowAnimated, 'RainbowAnimatedStaff');
export const RainbowAnimatedBirthdays = lazyWidget<ThemeWidgetProps>(loadThemesRainbowAnimated, 'RainbowAnimatedBirthdays');
export const RainbowAnimatedTicker = lazyWidget<ThemeWidgetProps>(loadThemesRainbowAnimated, 'RainbowAnimatedTicker');

const loadThemesFieldDay = () => import('./themes/field-day');
export const FieldDayLogo = lazyWidget<ThemeWidgetProps>(loadThemesFieldDay, 'FieldDayLogo');
export const FieldDayText = lazyWidget<ThemeWidgetProps>(loadThemesFieldDay, 'FieldDayText');
export const FieldDayClock = lazyWidget<ThemeWidgetProps>(loadThemesFieldDay, 'FieldDayClock');
export const FieldDayWeather = lazyWidget<ThemeWidgetProps>(loadThemesFieldDay, 'FieldDayWeather');
export const FieldDayCountdown = lazyWidget<ThemeWidgetProps>(loadThemesFieldDay, 'FieldDayCountdown');
export const FieldDayAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesFieldDay, 'FieldDayAnnouncement');
export const FieldDayCalendar = lazyWidget<ThemeWidgetProps>(loadThemesFieldDay, 'FieldDayCalendar');
export const FieldDayStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesFieldDay, 'FieldDayStaffSpotlight');
export const FieldDayImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesFieldDay, 'FieldDayImageCarousel');
export const FieldDayTicker = lazyWidget<ThemeWidgetProps>(loadThemesFieldDay, 'FieldDayTicker');

const loadThemesBulletinBoard = () => import('./themes/bulletin-board');
export const BulletinBoardLogo = lazyWidget<ThemeWidgetProps>(loadThemesBulletinBoard, 'BulletinBoardLogo');
export const BulletinBoardText = lazyWidget<ThemeWidgetProps>(loadThemesBulletinBoard, 'BulletinBoardText');
export const BulletinBoardClock = lazyWidget<ThemeWidgetProps>(loadThemesBulletinBoard, 'BulletinBoardClock');
export const BulletinBoardWeather = lazyWidget<ThemeWidgetProps>(loadThemesBulletinBoard, 'BulletinBoardWeather');
export const BulletinBoardCountdown = lazyWidget<ThemeWidgetProps>(loadThemesBulletinBoard, 'BulletinBoardCountdown');
export const BulletinBoardAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesBulletinBoard, 'BulletinBoardAnnouncement');
export const BulletinBoardCalendar = lazyWidget<ThemeWidgetProps>(loadThemesBulletinBoard, 'BulletinBoardCalendar');
export const BulletinBoardStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesBulletinBoard, 'BulletinBoardStaffSpotlight');
export const BulletinBoardImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesBulletinBoard, 'BulletinBoardImageCarousel');
export const BulletinBoardTicker = lazyWidget<ThemeWidgetProps>(loadThemesBulletinBoard, 'BulletinBoardTicker');

const loadThemesStorybook = () => import('./themes/storybook');
export const StorybookLogo = lazyWidget<ThemeWidgetProps>(loadThemesStorybook, 'StorybookLogo');
export const StorybookText = lazyWidget<ThemeWidgetProps>(loadThemesStorybook, 'StorybookText');
export const StorybookClock = lazyWidget<ThemeWidgetProps>(loadThemesStorybook, 'StorybookClock');
export const StorybookWeather = lazyWidget<ThemeWidgetProps>(loadThemesStorybook, 'StorybookWeather');
export const StorybookCountdown = lazyWidget<ThemeWidgetProps>(loadThemesStorybook, 'StorybookCountdown');
export const StorybookAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesStorybook, 'StorybookAnnouncement');
export const StorybookCalendar = lazyWidget<ThemeWidgetProps>(loadThemesStorybook, 'StorybookCalendar');
export const StorybookStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesStorybook, 'StorybookStaffSpotlight');
export const StorybookImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesStorybook, 'StorybookImageCarousel');
export const StorybookTicker = lazyWidget<ThemeWidgetProps>(loadThemesStorybook, 'StorybookTicker');

const loadThemesTrackDay = () => import('./themes/track-day');
export const TrackDayLogo = lazyWidget<ThemeWidgetProps>(loadThemesTrackDay, 'TrackDayLogo');
export const TrackDayText = lazyWidget<ThemeWidgetProps>(loadThemesTrackDay, 'TrackDayText');
export const TrackDayClock = lazyWidget<ThemeWidgetProps>(loadThemesTrackDay, 'TrackDayClock');
export const TrackDayWeather = lazyWidget<ThemeWidgetProps>(loadThemesTrackDay, 'TrackDayWeather');
export const TrackDayCountdown = lazyWidget<ThemeWidgetProps>(loadThemesTrackDay, 'TrackDayCountdown');
export const TrackDayAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesTrackDay, 'TrackDayAnnouncement');
export const TrackDayCalendar = lazyWidget<ThemeWidgetProps>(loadThemesTrackDay, 'TrackDayCalendar');
export const TrackDayStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesTrackDay, 'TrackDayStaffSpotlight');
export const TrackDayImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesTrackDay, 'TrackDayImageCarousel');
export const TrackDayTicker = lazyWidget<ThemeWidgetProps>(loadThemesTrackDay, 'TrackDayTicker');

const loadThemesScorebug = () => import('./themes/scorebug');
export const ScorebugLogo = lazyWidget<ThemeWidgetProps>(loadThemesScorebug, 'ScorebugLogo');
export const ScorebugText = lazyWidget<ThemeWidgetProps>(loadThemesScorebug, 'ScorebugText');
export const ScorebugClock = lazyWidget<ThemeWidgetProps>(loadThemesScorebug, 'ScorebugClock');
export const ScorebugWeather = lazyWidget<ThemeWidgetProps>(loadThemesScorebug, 'ScorebugWeather');
export const ScorebugCountdown = lazyWidget<ThemeWidgetProps>(loadThemesScorebug, 'ScorebugCountdown');
export const ScorebugAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesScorebug, 'ScorebugAnnouncement');
export const ScorebugCalendar = lazyWidget<ThemeWidgetProps>(loadThemesScorebug, 'ScorebugCalendar');
export const ScorebugStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesScorebug, 'ScorebugStaffSpotlight');
export const ScorebugImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesScorebug, 'ScorebugImageCarousel');
export const ScorebugTicker = lazyWidget<ThemeWidgetProps>(loadThemesScorebug, 'ScorebugTicker');

const loadThemesJumbotronPro = () => import('./themes/jumbotron-pro');
export const JumbotronProLogo = lazyWidget<ThemeWidgetProps>(loadThemesJumbotronPro, 'JumbotronProLogo');
export const JumbotronProText = lazyWidget<ThemeWidgetProps>(loadThemesJumbotronPro, 'JumbotronProText');
export const JumbotronProClock = lazyWidget<ThemeWidgetProps>(loadThemesJumbotronPro, 'JumbotronProClock');
export const JumbotronProWeather = lazyWidget<ThemeWidgetProps>(loadThemesJumbotronPro, 'JumbotronProWeather');
export const JumbotronProCountdown = lazyWidget<ThemeWidgetProps>(loadThemesJumbotronPro, 'JumbotronProCountdown');
export const JumbotronProAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesJumbotronPro, 'JumbotronProAnnouncement');
export const JumbotronProCalendar = lazyWidget<ThemeWidgetProps>(loadThemesJumbotronPro, 'JumbotronProCalendar');
export const JumbotronProStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesJumbotronPro, 'JumbotronProStaffSpotlight');
export const JumbotronProImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesJumbotronPro, 'JumbotronProImageCarousel');
export const JumbotronProTicker = lazyWidget<ThemeWidgetProps>(loadThemesJumbotronPro, 'JumbotronProTicker');

// 8 generic (theme-agnostic) widgets for launch: QUOTE, STATS,
// MENU_ITEM, SCOREBOARD, SCHEDULE_GRID, ATTENDANCE, BIRTHDAYS, HONOR_ROLL.
const loadThemesGenericWidgets = () => import('./themes/GenericWidgets');
export const QuoteWidget = lazyWidget<ThemeWidgetProps>(loadThemesGenericWidgets, 'QuoteWidget');
export const StatsWidget = lazyWidget<ThemeWidgetProps>(loadThemesGenericWidgets, 'StatsWidget');
export const MenuItemWidget = lazyWidget<ThemeWidgetProps>(loadThemesGenericWidgets, 'MenuItemWidget');
export const ScoreboardWidget = lazyWidget<ThemeWidgetProps>(loadThemesGenericWidgets, 'ScoreboardWidget');
export const ScheduleGridWidget = lazyWidget<ThemeWidgetProps>(loadThemesGenericWidgets, 'ScheduleGridWidget');
export const AttendanceWidget = lazyWidget<ThemeWidgetProps>(loadThemesGenericWidgets, 'AttendanceWidget');
export const BirthdaysWidget = lazyWidget<ThemeWidgetProps>(loadThemesGenericWidgets, 'BirthdaysWidget');
export const HonorRollWidget = lazyWidget<ThemeWidgetProps>(loadThemesGenericWidgets, 'HonorRollWidget');

const loadAnimatedWelcomeWidget = () => import('./AnimatedWelcomeWidget');
export const AnimatedWelcomeWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedWelcomeWidget, 'AnimatedWelcomeWidget');

const loadAnimatedWelcomePortraitWidget = () => import('./AnimatedWelcomePortraitWidget');
export const AnimatedWelcomePortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedWelcomePortraitWidget, 'AnimatedWelcomePortraitWidget');

// Sprint 13 — sport-bound widget primitives. These read live Game
// state from <GameStateProvider gameId> wrapped around the template
// render on /board /ribbon /scorebug; in the builder canvas (no
// provider) they render the config's `placeholder` instead.
const loadSportsSportWidgets = () => import('./sports/SportWidgets');
export const ScoreHomeWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportWidgets, 'ScoreHomeWidget');
export const ScoreAwayWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportWidgets, 'ScoreAwayWidget');
export const GameClockWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportWidgets, 'GameClockWidget');
export const GameSegmentWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportWidgets, 'GameSegmentWidget');
export const GameStatWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportWidgets, 'GameStatWidget');

// 2026-07-01 — swim/dive sport split flagship widgets. SWIM_LANE_GRID is
// the lane/heat/time board; DIVE_LEADERBOARD is the judged running-total
// leaderboard (diving has NO lanes/clock/splits — a different sport).
// 2026-07-01 DEPTH PASS — swim/dive widgets #3-6 (relay exchange, splits
// panel, record line, dive judges panel). See SwimDiveWidgets.tsx header.
const loadSportsSwimDiveWidgets = () => import('./sports/SwimDiveWidgets');
export const SwimLaneGridWidget = lazyWidget<ThemeWidgetProps>(loadSportsSwimDiveWidgets, 'SwimLaneGridWidget');
export const DiveLeaderboardWidget = lazyWidget<ThemeWidgetProps>(loadSportsSwimDiveWidgets, 'DiveLeaderboardWidget');
export const SwimRelayExchangeWidget = lazyWidget<ThemeWidgetProps>(loadSportsSwimDiveWidgets, 'SwimRelayExchangeWidget');
export const SwimSplitsPanelWidget = lazyWidget<ThemeWidgetProps>(loadSportsSwimDiveWidgets, 'SwimSplitsPanelWidget');
export const SwimRecordLineWidget = lazyWidget<ThemeWidgetProps>(loadSportsSwimDiveWidgets, 'SwimRecordLineWidget');
export const DiveJudgesPanelWidget = lazyWidget<ThemeWidgetProps>(loadSportsSwimDiveWidgets, 'DiveJudgesPanelWidget');

// S6 #288 (2026-07-03) — "Stadium Lane" flagship swim-meet broadcast
// board (v1 "Broadcast" only — v2/v3 reserved for later). A NEW widget
// file, not a SwimDiveWidgets reskin, so it doesn't collide with the
// concurrent no-fake-data sweep on that file. See
// StadiumMeetBoardWidget.tsx header for the full live-data mapping.
const loadSportsStadiumMeetBoardWidget = () => import('./sports/StadiumMeetBoardWidget');
export const StadiumMeetBoardWidget = lazyWidget<ThemeWidgetProps>(loadSportsStadiumMeetBoardWidget, 'StadiumMeetBoardWidget');

// ── Fitness vertical (Phase 1) — these are the first widgets for a
// non-EDU vertical. Kept in a dedicated /fitness subdir so the EDU
// import list up top stays readable + so we can fan these into
// `variants-register` later without mixing verticals. ──
const loadFitnessFitnessMusicPlayerWidget = () => import('./fitness/FitnessMusicPlayerWidget');
export const FitnessMusicPlayerWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessMusicPlayerWidget, 'FitnessMusicPlayerWidget');

const loadFitnessFitnessLiveTVWidget = () => import('./fitness/FitnessLiveTVWidget');
export const FitnessLiveTVWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessLiveTVWidget, 'FitnessLiveTVWidget');

const loadFitnessFitnessAdBannerWidget = () => import('./fitness/FitnessAdBannerWidget');
export const FitnessAdBannerWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessAdBannerWidget, 'FitnessAdBannerWidget');

const loadFitnessFitnessClassScheduleWidget = () => import('./fitness/FitnessClassScheduleWidget');
export const FitnessClassScheduleWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessClassScheduleWidget, 'FitnessClassScheduleWidget');

const loadFitnessFitnessTrainingVideoWidget = () => import('./fitness/FitnessTrainingVideoWidget');
export const FitnessTrainingVideoWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessTrainingVideoWidget, 'FitnessTrainingVideoWidget');

// 2026-05-03 — Sprint 8c streaming integrations. New STREAMING widget
// type backs the gym/bar/restaurant streaming framework: HLS / DASH /
// iframe playback + scheduled ad overlays. Channels resolve to a
// playback URL via /streaming/channels/:id (server-side signed URLs
// for providers that need auth).
const loadStreamingWidget = () => import('./StreamingWidget');
export const StreamingWidget = lazyWidget<ThemeWidgetProps>(loadStreamingWidget, 'StreamingWidget');

// 2026-05-25 monetize-audit — drop-in widget for the "house-only"
// ad network. Operator-uploaded creatives rotate with sponsor
// disclosure + optional CTA chip. NOT wired to the paid impression
// endpoint — running up impression counts for house ads would
// distort revenue reporting.
const loadHouseAdsBannerWidget = () => import('./HouseAdsBannerWidget');
export const HouseAdsBannerWidget = lazyWidget<ThemeWidgetProps>(loadHouseAdsBannerWidget, 'HouseAdsBannerWidget');

// 2026-05-25 music-overhaul — Spotify-for-Business / Apple Music for
// Business / SomaFM / NPR / NTS / generic stream. One widget, many
// source providers, server-resolved station list.
const loadMusicPlayerWidget = () => import('./MusicPlayerWidget');
export const MusicPlayerWidget = lazyWidget<ThemeWidgetProps>(loadMusicPlayerWidget, 'MusicPlayerWidget');

const loadFitnessFitnessWorkoutTimerWidget = () => import('./fitness/FitnessWorkoutTimerWidget');
export const FitnessWorkoutTimerWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessWorkoutTimerWidget, 'FitnessWorkoutTimerWidget');

const loadFitnessFitnessMotivationalQuoteWidget = () => import('./fitness/FitnessMotivationalQuoteWidget');
export const FitnessMotivationalQuoteWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessMotivationalQuoteWidget, 'FitnessMotivationalQuoteWidget');

const loadFitnessFitnessAppLibraryWidget = () => import('./fitness/FitnessAppLibraryWidget');
export const FitnessAppLibraryWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessAppLibraryWidget, 'FitnessAppLibraryWidget');

// 4K themed fitness scenes — full-canvas widgets ported from
// scratch/design/fitness/01-15.html. One drop-zone fills the canvas;
// every editable text node has a `data-field` attribute that the
// auto-form generator in PropertiesPanel picks up via DEFAULTS exports.
const loadFitnessFitnessStadiumWidget = () => import('./fitness/FitnessStadiumWidget');
export const FitnessStadiumWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessStadiumWidget, 'FitnessStadiumWidget');

const loadFitnessFitnessIronWidget = () => import('./fitness/FitnessIronWidget');
export const FitnessIronWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessIronWidget, 'FitnessIronWidget');

const loadFitnessFitnessMarqueeWidget = () => import('./fitness/FitnessMarqueeWidget');
export const FitnessMarqueeWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessMarqueeWidget, 'FitnessMarqueeWidget');

const loadFitnessFitnessChannelGuideWidget = () => import('./fitness/FitnessChannelGuideWidget');
export const FitnessChannelGuideWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessChannelGuideWidget, 'FitnessChannelGuideWidget');

const loadFitnessFitnessDiscothequeWidget = () => import('./fitness/FitnessDiscothequeWidget');
export const FitnessDiscothequeWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessDiscothequeWidget, 'FitnessDiscothequeWidget');

const loadFitnessFitnessLockerWidget = () => import('./fitness/FitnessLockerWidget');
export const FitnessLockerWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessLockerWidget, 'FitnessLockerWidget');

const loadFitnessFitnessSplashWidget = () => import('./fitness/FitnessSplashWidget');
export const FitnessSplashWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessSplashWidget, 'FitnessSplashWidget');

const loadFitnessFitnessTelemetryWidget = () => import('./fitness/FitnessTelemetryWidget');
export const FitnessTelemetryWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessTelemetryWidget, 'FitnessTelemetryWidget');

const loadFitnessFitnessCragWidget = () => import('./fitness/FitnessCragWidget');
export const FitnessCragWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessCragWidget, 'FitnessCragWidget');

const loadFitnessFitnessCornermanWidget = () => import('./fitness/FitnessCornermanWidget');
export const FitnessCornermanWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessCornermanWidget, 'FitnessCornermanWidget');

const loadFitnessFitnessRecessWidget = () => import('./fitness/FitnessRecessWidget');
export const FitnessRecessWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessRecessWidget, 'FitnessRecessWidget');

const loadFitnessFitnessReformerWidget = () => import('./fitness/FitnessReformerWidget');
export const FitnessReformerWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessReformerWidget, 'FitnessReformerWidget');

const loadFitnessFitnessTrailheadWidget = () => import('./fitness/FitnessTrailheadWidget');
export const FitnessTrailheadWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessTrailheadWidget, 'FitnessTrailheadWidget');

const loadFitnessFitnessVaultWidget = () => import('./fitness/FitnessVaultWidget');
export const FitnessVaultWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessVaultWidget, 'FitnessVaultWidget');

const loadFitnessFitnessLobbyWidget = () => import('./fitness/FitnessLobbyWidget');
export const FitnessLobbyWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessLobbyWidget, 'FitnessLobbyWidget');

const loadFitnessFitnessStickLauncherWidget = () => import('./fitness/FitnessStickLauncherWidget');
export const FitnessStickLauncherWidget = lazyWidget<ThemeWidgetProps>(loadFitnessFitnessStickLauncherWidget, 'FitnessStickLauncherWidget');

// ── Restaurant / QSR vertical (2026-05-02) — menu boards, combos,
// loyalty, wait-time, specials. Same /restaurant subdir convention as
// /fitness so the EDU import list above stays uncluttered. ──
const loadRestaurantMenuBoardWidget = () => import('./restaurant/MenuBoardWidget');
export const MenuBoardWidget = lazyWidget<ThemeWidgetProps>(loadRestaurantMenuBoardWidget, 'MenuBoardWidget');

const loadRestaurantComboCarouselWidget = () => import('./restaurant/ComboCarouselWidget');
export const ComboCarouselWidget = lazyWidget<ThemeWidgetProps>(loadRestaurantComboCarouselWidget, 'ComboCarouselWidget');

const loadRestaurantWaitTimeWidget = () => import('./restaurant/WaitTimeWidget');
export const WaitTimeWidget = lazyWidget<ThemeWidgetProps>(loadRestaurantWaitTimeWidget, 'WaitTimeWidget');

const loadRestaurantLoyaltyTickerWidget = () => import('./restaurant/LoyaltyTickerWidget');
export const LoyaltyTickerWidget = lazyWidget<ThemeWidgetProps>(loadRestaurantLoyaltyTickerWidget, 'LoyaltyTickerWidget');

const loadRestaurantSpecialsCalloutWidget = () => import('./restaurant/SpecialsCalloutWidget');
export const SpecialsCalloutWidget = lazyWidget<ThemeWidgetProps>(loadRestaurantSpecialsCalloutWidget, 'SpecialsCalloutWidget');

const loadRestaurantAllergyLegendWidget = () => import('./restaurant/AllergyLegendWidget');
export const AllergyLegendWidget = lazyWidget<ThemeWidgetProps>(loadRestaurantAllergyLegendWidget, 'AllergyLegendWidget');

// ── BAR / nightlife vertical (2026-05-02) — taproom + sports pub +
// nightclub widgets. Visual DNA: charcoal + amber + neon, hand-drawn
// chalkboard for cocktails, stadium scoreboard for trivia / game-day.
// Lives in /bar so the file list stays grouped per vertical. ──
const loadBarTapListWidget = () => import('./bar/TapListWidget');
export const TapListWidget = lazyWidget<ThemeWidgetProps>(loadBarTapListWidget, 'TapListWidget');

const loadBarCocktailMenuWidget = () => import('./bar/CocktailMenuWidget');
export const CocktailMenuWidget = lazyWidget<ThemeWidgetProps>(loadBarCocktailMenuWidget, 'CocktailMenuWidget');

const loadBarHappyHourCountdownWidget = () => import('./bar/HappyHourCountdownWidget');
export const HappyHourCountdownWidget = lazyWidget<ThemeWidgetProps>(loadBarHappyHourCountdownWidget, 'HappyHourCountdownWidget');

const loadBarGameDayScheduleWidget = () => import('./bar/GameDayScheduleWidget');
export const GameDayScheduleWidget = lazyWidget<ThemeWidgetProps>(loadBarGameDayScheduleWidget, 'GameDayScheduleWidget');

const loadBarEventTonightWidget = () => import('./bar/EventTonightWidget');
export const EventTonightWidget = lazyWidget<ThemeWidgetProps>(loadBarEventTonightWidget, 'EventTonightWidget');

const loadBarTriviaScoreboardWidget = () => import('./bar/TriviaScoreboardWidget');
export const TriviaScoreboardWidget = lazyWidget<ThemeWidgetProps>(loadBarTriviaScoreboardWidget, 'TriviaScoreboardWidget');

// Retail widget imports — paired with the dispatch cases below.
// Parallel agent shipped these files but ran out of tokens before
// adding the imports + case statements; finishing now.
const loadRetailRetailProductGridWidget = () => import('./retail/RetailProductGridWidget');
export const RetailProductGridWidget = lazyWidget<ThemeWidgetProps>(loadRetailRetailProductGridWidget, 'RetailProductGridWidget');

const loadRetailRetailPriceCalloutWidget = () => import('./retail/RetailPriceCalloutWidget');
export const RetailPriceCalloutWidget = lazyWidget<ThemeWidgetProps>(loadRetailRetailPriceCalloutWidget, 'RetailPriceCalloutWidget');

const loadRetailRetailSaleCountdownWidget = () => import('./retail/RetailSaleCountdownWidget');
export const RetailSaleCountdownWidget = lazyWidget<ThemeWidgetProps>(loadRetailRetailSaleCountdownWidget, 'RetailSaleCountdownWidget');

const loadRetailRetailWayfindingMapWidget = () => import('./retail/RetailWayfindingMapWidget');
export const RetailWayfindingMapWidget = lazyWidget<ThemeWidgetProps>(loadRetailRetailWayfindingMapWidget, 'RetailWayfindingMapWidget');

const loadRetailRetailLoyaltyQRWidget = () => import('./retail/RetailLoyaltyQRWidget');
export const RetailLoyaltyQRWidget = lazyWidget<ThemeWidgetProps>(loadRetailRetailLoyaltyQRWidget, 'RetailLoyaltyQRWidget');

const loadRetailRetailLookbookCarouselWidget = () => import('./retail/RetailLookbookCarouselWidget');
export const RetailLookbookCarouselWidget = lazyWidget<ThemeWidgetProps>(loadRetailRetailLookbookCarouselWidget, 'RetailLookbookCarouselWidget');

const loadRetailRetailStorefrontHoursWidget = () => import('./retail/RetailStorefrontHoursWidget');
export const RetailStorefrontHoursWidget = lazyWidget<ThemeWidgetProps>(loadRetailRetailStorefrontHoursWidget, 'RetailStorefrontHoursWidget');

const loadAnimatedWelcomeMiddleWidget = () => import('./AnimatedWelcomeMiddleWidget');
export const AnimatedWelcomeMiddleWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedWelcomeMiddleWidget, 'AnimatedWelcomeMiddleWidget');

const loadAnimatedWelcomeHighWidget = () => import('./AnimatedWelcomeHighWidget');
export const AnimatedWelcomeHighWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedWelcomeHighWidget, 'AnimatedWelcomeHighWidget');

const loadAnimatedCafeteriaElementaryWidget = () => import('./AnimatedCafeteriaElementaryWidget');
export const AnimatedCafeteriaElementaryWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedCafeteriaElementaryWidget, 'AnimatedCafeteriaElementaryWidget');

const loadAnimatedBackgroundWidget = () => import('./AnimatedBackgroundWidget');
export const AnimatedBackgroundWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedBackgroundWidget, 'AnimatedBackgroundWidget');

// Claude-designed HS lobby pack (2026-04-23). Each scene is a 4K
// stage from scratch/design/hs/*.html, wrapped in HsStage for
// transform:scale. Eight themes total; Varsity ships first as the
// exemplar; the rest land in a follow-up commit.
const loadHsHsVarsityWidget = () => import('./hs/HsVarsityWidget');
export const HsVarsityWidget = lazyWidget<ThemeWidgetProps>(loadHsHsVarsityWidget, 'HsVarsityWidget');

const loadHsHsBroadcastWidget = () => import('./hs/HsBroadcastWidget');
export const HsBroadcastWidget = lazyWidget<ThemeWidgetProps>(loadHsHsBroadcastWidget, 'HsBroadcastWidget');

const loadHsHsYearbookWidget = () => import('./hs/HsYearbookWidget');
export const HsYearbookWidget = lazyWidget<ThemeWidgetProps>(loadHsHsYearbookWidget, 'HsYearbookWidget');

const loadHsHsTerminalWidget = () => import('./hs/HsTerminalWidget');
export const HsTerminalWidget = lazyWidget<ThemeWidgetProps>(loadHsHsTerminalWidget, 'HsTerminalWidget');

const loadHsHsTransitWidget = () => import('./hs/HsTransitWidget');
export const HsTransitWidget = lazyWidget<ThemeWidgetProps>(loadHsHsTransitWidget, 'HsTransitWidget');

const loadHsHsGalleryWidget = () => import('./hs/HsGalleryWidget');
export const HsGalleryWidget = lazyWidget<ThemeWidgetProps>(loadHsHsGalleryWidget, 'HsGalleryWidget');

const loadHsHsBlueprintWidget = () => import('./hs/HsBlueprintWidget');
export const HsBlueprintWidget = lazyWidget<ThemeWidgetProps>(loadHsHsBlueprintWidget, 'HsBlueprintWidget');

const loadHsHsZineWidget = () => import('./hs/HsZineWidget');
export const HsZineWidget = lazyWidget<ThemeWidgetProps>(loadHsHsZineWidget, 'HsZineWidget');

// MS Pack — first port (Arcade), pattern matches HS templates.
const loadMsMsArcadeWidget = () => import('./ms/MsArcadeWidget');
export const MsArcadeWidget = lazyWidget<ThemeWidgetProps>(loadMsMsArcadeWidget, 'MsArcadeWidget');

const loadMsMsAtlasWidget = () => import('./ms/MsAtlasWidget');
export const MsAtlasWidget = lazyWidget<ThemeWidgetProps>(loadMsMsAtlasWidget, 'MsAtlasWidget');

const loadMsMsFieldnotesWidget = () => import('./ms/MsFieldnotesWidget');
export const MsFieldnotesWidget = lazyWidget<ThemeWidgetProps>(loadMsMsFieldnotesWidget, 'MsFieldnotesWidget');

const loadMsMsGreenhouseWidget = () => import('./ms/MsGreenhouseWidget');
export const MsGreenhouseWidget = lazyWidget<ThemeWidgetProps>(loadMsMsGreenhouseWidget, 'MsGreenhouseWidget');

const loadMsMsHomeroomWidget = () => import('./ms/MsHomeroomWidget');
export const MsHomeroomWidget = lazyWidget<ThemeWidgetProps>(loadMsMsHomeroomWidget, 'MsHomeroomWidget');

const loadMsMsPaperWidget = () => import('./ms/MsPaperWidget');
export const MsPaperWidget = lazyWidget<ThemeWidgetProps>(loadMsMsPaperWidget, 'MsPaperWidget');

const loadMsMsPlaylistWidget = () => import('./ms/MsPlaylistWidget');
export const MsPlaylistWidget = lazyWidget<ThemeWidgetProps>(loadMsMsPlaylistWidget, 'MsPlaylistWidget');

const loadMsMsStudioWidget = () => import('./ms/MsStudioWidget');
export const MsStudioWidget = lazyWidget<ThemeWidgetProps>(loadMsMsStudioWidget, 'MsStudioWidget');

const loadMsMsArcadePortraitWidget = () => import('./ms/MsArcadePortraitWidget');
export const MsArcadePortraitWidget = lazyWidget<ThemeWidgetProps>(loadMsMsArcadePortraitWidget, 'MsArcadePortraitWidget');

const loadMsMsAtlasPortraitWidget = () => import('./ms/MsAtlasPortraitWidget');
export const MsAtlasPortraitWidget = lazyWidget<ThemeWidgetProps>(loadMsMsAtlasPortraitWidget, 'MsAtlasPortraitWidget');

const loadMsMsFieldnotesPortraitWidget = () => import('./ms/MsFieldnotesPortraitWidget');
export const MsFieldnotesPortraitWidget = lazyWidget<ThemeWidgetProps>(loadMsMsFieldnotesPortraitWidget, 'MsFieldnotesPortraitWidget');

const loadMsMsGreenhousePortraitWidget = () => import('./ms/MsGreenhousePortraitWidget');
export const MsGreenhousePortraitWidget = lazyWidget<ThemeWidgetProps>(loadMsMsGreenhousePortraitWidget, 'MsGreenhousePortraitWidget');

const loadMsMsHomeroomPortraitWidget = () => import('./ms/MsHomeroomPortraitWidget');
export const MsHomeroomPortraitWidget = lazyWidget<ThemeWidgetProps>(loadMsMsHomeroomPortraitWidget, 'MsHomeroomPortraitWidget');

const loadMsMsPaperPortraitWidget = () => import('./ms/MsPaperPortraitWidget');
export const MsPaperPortraitWidget = lazyWidget<ThemeWidgetProps>(loadMsMsPaperPortraitWidget, 'MsPaperPortraitWidget');

const loadMsMsPlaylistPortraitWidget = () => import('./ms/MsPlaylistPortraitWidget');
export const MsPlaylistPortraitWidget = lazyWidget<ThemeWidgetProps>(loadMsMsPlaylistPortraitWidget, 'MsPlaylistPortraitWidget');

const loadMsMsStudioPortraitWidget = () => import('./ms/MsStudioPortraitWidget');
export const MsStudioPortraitWidget = lazyWidget<ThemeWidgetProps>(loadMsMsStudioPortraitWidget, 'MsStudioPortraitWidget');

// 16 templates ported from scratch/design/*.html (4 parallel agents, 2026-04-20).
// Each widget is a full-screen scene (transform:scale 1920×1080 pattern, live-
// gated hotspots, ticker-speed helper). See CLAUDE.md "Template Design
// Workflow" for the port rules.
const loadAnimatedCafeteriaMiddleWidget = () => import('./AnimatedCafeteriaMiddleWidget');
export const AnimatedCafeteriaMiddleWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedCafeteriaMiddleWidget, 'AnimatedCafeteriaMiddleWidget');

const loadAnimatedCafeteriaHighWidget = () => import('./AnimatedCafeteriaHighWidget');
export const AnimatedCafeteriaHighWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedCafeteriaHighWidget, 'AnimatedCafeteriaHighWidget');

const loadAnimatedBusBoardWidget = () => import('./AnimatedBusBoardWidget');
export const AnimatedBusBoardWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedBusBoardWidget, 'AnimatedBusBoardWidget');

const loadAnimatedMainEntranceWidget = () => import('./AnimatedMainEntranceWidget');
export const AnimatedMainEntranceWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedMainEntranceWidget, 'AnimatedMainEntranceWidget');

const loadAnimatedHallwayScheduleWidget = () => import('./AnimatedHallwayScheduleWidget');
export const AnimatedHallwayScheduleWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedHallwayScheduleWidget, 'AnimatedHallwayScheduleWidget');

const loadAnimatedBellScheduleWidget = () => import('./AnimatedBellScheduleWidget');
export const AnimatedBellScheduleWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedBellScheduleWidget, 'AnimatedBellScheduleWidget');

const loadAnimatedMorningNewsWidget = () => import('./AnimatedMorningNewsWidget');
export const AnimatedMorningNewsWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedMorningNewsWidget, 'AnimatedMorningNewsWidget');

const loadAnimatedAchievementShowcaseWidget = () => import('./AnimatedAchievementShowcaseWidget');
export const AnimatedAchievementShowcaseWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedAchievementShowcaseWidget, 'AnimatedAchievementShowcaseWidget');

const loadScrapbookHallwayWidget = () => import('./ScrapbookHallwayWidget');
export const ScrapbookHallwayWidget = lazyWidget<ThemeWidgetProps>(loadScrapbookHallwayWidget, 'ScrapbookHallwayWidget');

// Real 4K portrait companions — vertical re-flow at 2160x3840.
const loadAnimatedHallwaySchedulePortraitWidget = () => import('./AnimatedHallwaySchedulePortraitWidget');
export const AnimatedHallwaySchedulePortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedHallwaySchedulePortraitWidget, 'AnimatedHallwaySchedulePortraitWidget');

const loadAnimatedBellSchedulePortraitWidget = () => import('./AnimatedBellSchedulePortraitWidget');
export const AnimatedBellSchedulePortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedBellSchedulePortraitWidget, 'AnimatedBellSchedulePortraitWidget');

const loadAnimatedCafeteriaFoodtruckPortraitWidget = () => import('./AnimatedCafeteriaFoodtruckPortraitWidget');
export const AnimatedCafeteriaFoodtruckPortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedCafeteriaFoodtruckPortraitWidget, 'AnimatedCafeteriaFoodtruckPortraitWidget');

// Sprint 11i pre-demo wave (2026-04-27): 8 more real 4K portrait widgets
// dispatched in parallel agent batch. Each is 2160x3840 native, NOT a
// landscape letterboxed into a vertical frame.
const loadAnimatedBusBoardPortraitWidget = () => import('./AnimatedBusBoardPortraitWidget');
export const AnimatedBusBoardPortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedBusBoardPortraitWidget, 'AnimatedBusBoardPortraitWidget');

const loadAnimatedMainEntrancePortraitWidget = () => import('./AnimatedMainEntrancePortraitWidget');
export const AnimatedMainEntrancePortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedMainEntrancePortraitWidget, 'AnimatedMainEntrancePortraitWidget');

const loadAnimatedMorningNewsPortraitWidget = () => import('./AnimatedMorningNewsPortraitWidget');
export const AnimatedMorningNewsPortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedMorningNewsPortraitWidget, 'AnimatedMorningNewsPortraitWidget');

const loadAnimatedAchievementShowcasePortraitWidget = () => import('./AnimatedAchievementShowcasePortraitWidget');
export const AnimatedAchievementShowcasePortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedAchievementShowcasePortraitWidget, 'AnimatedAchievementShowcasePortraitWidget');

const loadAnimatedCafeteriaElementaryPortraitWidget = () => import('./AnimatedCafeteriaElementaryPortraitWidget');
export const AnimatedCafeteriaElementaryPortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedCafeteriaElementaryPortraitWidget, 'AnimatedCafeteriaElementaryPortraitWidget');

const loadAnimatedWelcomeHighPortraitWidget = () => import('./AnimatedWelcomeHighPortraitWidget');
export const AnimatedWelcomeHighPortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedWelcomeHighPortraitWidget, 'AnimatedWelcomeHighPortraitWidget');

const loadHsHsBlueprintPortraitWidget = () => import('./hs/HsBlueprintPortraitWidget');
export const HsBlueprintPortraitWidget = lazyWidget<ThemeWidgetProps>(loadHsHsBlueprintPortraitWidget, 'HsBlueprintPortraitWidget');

const loadHsHsVarsityPortraitWidget = () => import('./hs/HsVarsityPortraitWidget');
export const HsVarsityPortraitWidget = lazyWidget<ThemeWidgetProps>(loadHsHsVarsityPortraitWidget, 'HsVarsityPortraitWidget');

// Sprint 11i second wave (2026-04-27): the rest of the HS portrait pack
// + middle-school welcome / cafeteria portrait companions.
const loadAnimatedWelcomeMiddlePortraitWidget = () => import('./AnimatedWelcomeMiddlePortraitWidget');
export const AnimatedWelcomeMiddlePortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedWelcomeMiddlePortraitWidget, 'AnimatedWelcomeMiddlePortraitWidget');

const loadAnimatedCafeteriaMiddlePortraitWidget = () => import('./AnimatedCafeteriaMiddlePortraitWidget');
export const AnimatedCafeteriaMiddlePortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedCafeteriaMiddlePortraitWidget, 'AnimatedCafeteriaMiddlePortraitWidget');

const loadHsHsBroadcastPortraitWidget = () => import('./hs/HsBroadcastPortraitWidget');
export const HsBroadcastPortraitWidget = lazyWidget<ThemeWidgetProps>(loadHsHsBroadcastPortraitWidget, 'HsBroadcastPortraitWidget');

const loadHsHsGalleryPortraitWidget = () => import('./hs/HsGalleryPortraitWidget');
export const HsGalleryPortraitWidget = lazyWidget<ThemeWidgetProps>(loadHsHsGalleryPortraitWidget, 'HsGalleryPortraitWidget');

const loadHsHsTerminalPortraitWidget = () => import('./hs/HsTerminalPortraitWidget');
export const HsTerminalPortraitWidget = lazyWidget<ThemeWidgetProps>(loadHsHsTerminalPortraitWidget, 'HsTerminalPortraitWidget');

const loadHsHsTransitPortraitWidget = () => import('./hs/HsTransitPortraitWidget');
export const HsTransitPortraitWidget = lazyWidget<ThemeWidgetProps>(loadHsHsTransitPortraitWidget, 'HsTransitPortraitWidget');

const loadHsHsYearbookPortraitWidget = () => import('./hs/HsYearbookPortraitWidget');
export const HsYearbookPortraitWidget = lazyWidget<ThemeWidgetProps>(loadHsHsYearbookPortraitWidget, 'HsYearbookPortraitWidget');

const loadHsHsZinePortraitWidget = () => import('./hs/HsZinePortraitWidget');
export const HsZinePortraitWidget = lazyWidget<ThemeWidgetProps>(loadHsHsZinePortraitWidget, 'HsZinePortraitWidget');

// Sprint 11i FINAL wave (2026-04-27): 8 themed-cafeteria + hallway
// portraits — closes out the LETTERBOXED denylist. Catalog is now
// 100% real-portrait when the preset is marked PORTRAIT.
const loadBulletinCafeteriaPortraitWidget = () => import('./BulletinCafeteriaPortraitWidget');
export const BulletinCafeteriaPortraitWidget = lazyWidget<ThemeWidgetProps>(loadBulletinCafeteriaPortraitWidget, 'BulletinCafeteriaPortraitWidget');

const loadBulletinHallwayPortraitWidget = () => import('./BulletinHallwayPortraitWidget');
export const BulletinHallwayPortraitWidget = lazyWidget<ThemeWidgetProps>(loadBulletinHallwayPortraitWidget, 'BulletinHallwayPortraitWidget');

const loadAnimatedCafeteriaHighPortraitWidget = () => import('./AnimatedCafeteriaHighPortraitWidget');
export const AnimatedCafeteriaHighPortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedCafeteriaHighPortraitWidget, 'AnimatedCafeteriaHighPortraitWidget');

const loadAnimatedCafeteriaChalkboardPortraitWidget = () => import('./AnimatedCafeteriaChalkboardPortraitWidget');
export const AnimatedCafeteriaChalkboardPortraitWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedCafeteriaChalkboardPortraitWidget, 'AnimatedCafeteriaChalkboardPortraitWidget');

const loadScrapbookCafeteriaPortraitWidget = () => import('./ScrapbookCafeteriaPortraitWidget');
export const ScrapbookCafeteriaPortraitWidget = lazyWidget<ThemeWidgetProps>(loadScrapbookCafeteriaPortraitWidget, 'ScrapbookCafeteriaPortraitWidget');

const loadScrapbookHallwayPortraitWidget = () => import('./ScrapbookHallwayPortraitWidget');
export const ScrapbookHallwayPortraitWidget = lazyWidget<ThemeWidgetProps>(loadScrapbookHallwayPortraitWidget, 'ScrapbookHallwayPortraitWidget');

const loadStorybookCafeteriaPortraitWidget = () => import('./StorybookCafeteriaPortraitWidget');
export const StorybookCafeteriaPortraitWidget = lazyWidget<ThemeWidgetProps>(loadStorybookCafeteriaPortraitWidget, 'StorybookCafeteriaPortraitWidget');

const loadStorybookHallwayPortraitWidget = () => import('./StorybookHallwayPortraitWidget');
export const StorybookHallwayPortraitWidget = lazyWidget<ThemeWidgetProps>(loadStorybookHallwayPortraitWidget, 'StorybookHallwayPortraitWidget');

// Sprint 11h pre-launch: drag-drop animations as a generic decoration widget.
const loadDecorationWidget = () => import('./DecorationWidget');
export const DecorationWidget = lazyWidget<ThemeWidgetProps>(loadDecorationWidget, 'DecorationWidget');

// Wave B / editor-crush B2/B5 (2026-07-02) — static SHAPE + ICON elements.
const loadShapeWidget = () => import('./ShapeWidget');
export const ShapeWidget = lazyWidget<ThemeWidgetProps>(loadShapeWidget, 'ShapeWidget');

const loadIconWidget = () => import('./IconWidget');
export const IconWidget = lazyWidget<ThemeWidgetProps>(loadIconWidget, 'IconWidget');

// Holiday lobby pack — Halloween, Thanksgiving, Christmas, Valentine's,
// St. Patrick's, Easter × ES/MS/HS. Each renders a designed full-canvas
// scene from /public/holiday-templates/*.html via iframe (CSS isolation).
const loadHolidayWidget = () => import('./HolidayWidget');
export const HolidayWidget = lazyWidget<ThemeWidgetProps>(loadHolidayWidget, 'HolidayWidget');

const loadScrapbookCafeteriaWidget = () => import('./ScrapbookCafeteriaWidget');
export const ScrapbookCafeteriaWidget = lazyWidget<ThemeWidgetProps>(loadScrapbookCafeteriaWidget, 'ScrapbookCafeteriaWidget');

const loadStorybookHallwayWidget = () => import('./StorybookHallwayWidget');
export const StorybookHallwayWidget = lazyWidget<ThemeWidgetProps>(loadStorybookHallwayWidget, 'StorybookHallwayWidget');

const loadBulletinHallwayWidget = () => import('./BulletinHallwayWidget');
export const BulletinHallwayWidget = lazyWidget<ThemeWidgetProps>(loadBulletinHallwayWidget, 'BulletinHallwayWidget');

const loadStorybookCafeteriaWidget = () => import('./StorybookCafeteriaWidget');
export const StorybookCafeteriaWidget = lazyWidget<ThemeWidgetProps>(loadStorybookCafeteriaWidget, 'StorybookCafeteriaWidget');

const loadBulletinCafeteriaWidget = () => import('./BulletinCafeteriaWidget');
export const BulletinCafeteriaWidget = lazyWidget<ThemeWidgetProps>(loadBulletinCafeteriaWidget, 'BulletinCafeteriaWidget');

const loadAnimatedCafeteriaChalkboardWidget = () => import('./AnimatedCafeteriaChalkboardWidget');
export const AnimatedCafeteriaChalkboardWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedCafeteriaChalkboardWidget, 'AnimatedCafeteriaChalkboardWidget');

const loadAnimatedCafeteriaFoodtruckWidget = () => import('./AnimatedCafeteriaFoodtruckWidget');
export const AnimatedCafeteriaFoodtruckWidget = lazyWidget<ThemeWidgetProps>(loadAnimatedCafeteriaFoodtruckWidget, 'AnimatedCafeteriaFoodtruckWidget');

const loadThemesScrapbook = () => import('./themes/scrapbook');
export const ScrapbookLogo = lazyWidget<ThemeWidgetProps>(loadThemesScrapbook, 'ScrapbookLogo');
export const ScrapbookText = lazyWidget<ThemeWidgetProps>(loadThemesScrapbook, 'ScrapbookText');
export const ScrapbookClock = lazyWidget<ThemeWidgetProps>(loadThemesScrapbook, 'ScrapbookClock');
export const ScrapbookWeather = lazyWidget<ThemeWidgetProps>(loadThemesScrapbook, 'ScrapbookWeather');
export const ScrapbookCountdown = lazyWidget<ThemeWidgetProps>(loadThemesScrapbook, 'ScrapbookCountdown');
export const ScrapbookAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesScrapbook, 'ScrapbookAnnouncement');
export const ScrapbookCalendar = lazyWidget<ThemeWidgetProps>(loadThemesScrapbook, 'ScrapbookCalendar');
export const ScrapbookStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesScrapbook, 'ScrapbookStaffSpotlight');
export const ScrapbookImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesScrapbook, 'ScrapbookImageCarousel');
export const ScrapbookTicker = lazyWidget<ThemeWidgetProps>(loadThemesScrapbook, 'ScrapbookTicker');

const loadThemesLockerHallway = () => import('./themes/locker-hallway');
export const LockerHallwayLogo = lazyWidget<ThemeWidgetProps>(loadThemesLockerHallway, 'LockerHallwayLogo');
export const LockerHallwayText = lazyWidget<ThemeWidgetProps>(loadThemesLockerHallway, 'LockerHallwayText');
export const LockerHallwayClock = lazyWidget<ThemeWidgetProps>(loadThemesLockerHallway, 'LockerHallwayClock');
export const LockerHallwayWeather = lazyWidget<ThemeWidgetProps>(loadThemesLockerHallway, 'LockerHallwayWeather');
export const LockerHallwayCountdown = lazyWidget<ThemeWidgetProps>(loadThemesLockerHallway, 'LockerHallwayCountdown');
export const LockerHallwayAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesLockerHallway, 'LockerHallwayAnnouncement');
export const LockerHallwayCalendar = lazyWidget<ThemeWidgetProps>(loadThemesLockerHallway, 'LockerHallwayCalendar');
export const LockerHallwayStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesLockerHallway, 'LockerHallwayStaffSpotlight');
export const LockerHallwayImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesLockerHallway, 'LockerHallwayImageCarousel');
export const LockerHallwayTicker = lazyWidget<ThemeWidgetProps>(loadThemesLockerHallway, 'LockerHallwayTicker');

const loadThemesSpiritRally = () => import('./themes/spirit-rally');
export const SpiritRallyLogo = lazyWidget<ThemeWidgetProps>(loadThemesSpiritRally, 'SpiritRallyLogo');
export const SpiritRallyText = lazyWidget<ThemeWidgetProps>(loadThemesSpiritRally, 'SpiritRallyText');
export const SpiritRallyClock = lazyWidget<ThemeWidgetProps>(loadThemesSpiritRally, 'SpiritRallyClock');
export const SpiritRallyWeather = lazyWidget<ThemeWidgetProps>(loadThemesSpiritRally, 'SpiritRallyWeather');
export const SpiritRallyCountdown = lazyWidget<ThemeWidgetProps>(loadThemesSpiritRally, 'SpiritRallyCountdown');
export const SpiritRallyAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesSpiritRally, 'SpiritRallyAnnouncement');
export const SpiritRallyCalendar = lazyWidget<ThemeWidgetProps>(loadThemesSpiritRally, 'SpiritRallyCalendar');
export const SpiritRallyStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesSpiritRally, 'SpiritRallyStaffSpotlight');
export const SpiritRallyImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesSpiritRally, 'SpiritRallyImageCarousel');
export const SpiritRallyTicker = lazyWidget<ThemeWidgetProps>(loadThemesSpiritRally, 'SpiritRallyTicker');

const loadThemesStemLab = () => import('./themes/stem-lab');
export const StemLabLogo = lazyWidget<ThemeWidgetProps>(loadThemesStemLab, 'StemLabLogo');
export const StemLabText = lazyWidget<ThemeWidgetProps>(loadThemesStemLab, 'StemLabText');
export const StemLabClock = lazyWidget<ThemeWidgetProps>(loadThemesStemLab, 'StemLabClock');
export const StemLabWeather = lazyWidget<ThemeWidgetProps>(loadThemesStemLab, 'StemLabWeather');
export const StemLabCountdown = lazyWidget<ThemeWidgetProps>(loadThemesStemLab, 'StemLabCountdown');
export const StemLabAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesStemLab, 'StemLabAnnouncement');
export const StemLabCalendar = lazyWidget<ThemeWidgetProps>(loadThemesStemLab, 'StemLabCalendar');
export const StemLabStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesStemLab, 'StemLabStaffSpotlight');
export const StemLabImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesStemLab, 'StemLabImageCarousel');
export const StemLabTicker = lazyWidget<ThemeWidgetProps>(loadThemesStemLab, 'StemLabTicker');

const loadThemesMorningNews = () => import('./themes/morning-news');
export const MorningNewsLogo = lazyWidget<ThemeWidgetProps>(loadThemesMorningNews, 'MorningNewsLogo');
export const MorningNewsText = lazyWidget<ThemeWidgetProps>(loadThemesMorningNews, 'MorningNewsText');
export const MorningNewsClock = lazyWidget<ThemeWidgetProps>(loadThemesMorningNews, 'MorningNewsClock');
export const MorningNewsWeather = lazyWidget<ThemeWidgetProps>(loadThemesMorningNews, 'MorningNewsWeather');
export const MorningNewsCountdown = lazyWidget<ThemeWidgetProps>(loadThemesMorningNews, 'MorningNewsCountdown');
export const MorningNewsAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesMorningNews, 'MorningNewsAnnouncement');
export const MorningNewsCalendar = lazyWidget<ThemeWidgetProps>(loadThemesMorningNews, 'MorningNewsCalendar');
export const MorningNewsStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesMorningNews, 'MorningNewsStaffSpotlight');
export const MorningNewsImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesMorningNews, 'MorningNewsImageCarousel');
export const MorningNewsTicker = lazyWidget<ThemeWidgetProps>(loadThemesMorningNews, 'MorningNewsTicker');

const loadThemesArtStudio = () => import('./themes/art-studio');
export const ArtStudioLogo = lazyWidget<ThemeWidgetProps>(loadThemesArtStudio, 'ArtStudioLogo');
export const ArtStudioText = lazyWidget<ThemeWidgetProps>(loadThemesArtStudio, 'ArtStudioText');
export const ArtStudioClock = lazyWidget<ThemeWidgetProps>(loadThemesArtStudio, 'ArtStudioClock');
export const ArtStudioWeather = lazyWidget<ThemeWidgetProps>(loadThemesArtStudio, 'ArtStudioWeather');
export const ArtStudioCountdown = lazyWidget<ThemeWidgetProps>(loadThemesArtStudio, 'ArtStudioCountdown');
export const ArtStudioAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesArtStudio, 'ArtStudioAnnouncement');
export const ArtStudioCalendar = lazyWidget<ThemeWidgetProps>(loadThemesArtStudio, 'ArtStudioCalendar');
export const ArtStudioStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesArtStudio, 'ArtStudioStaffSpotlight');
export const ArtStudioImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesArtStudio, 'ArtStudioImageCarousel');
export const ArtStudioTicker = lazyWidget<ThemeWidgetProps>(loadThemesArtStudio, 'ArtStudioTicker');

const loadThemesVarsityAthletic = () => import('./themes/varsity-athletic');
export const VarsityAthleticLogo = lazyWidget<ThemeWidgetProps>(loadThemesVarsityAthletic, 'VarsityAthleticLogo');
export const VarsityAthleticText = lazyWidget<ThemeWidgetProps>(loadThemesVarsityAthletic, 'VarsityAthleticText');
export const VarsityAthleticClock = lazyWidget<ThemeWidgetProps>(loadThemesVarsityAthletic, 'VarsityAthleticClock');
export const VarsityAthleticWeather = lazyWidget<ThemeWidgetProps>(loadThemesVarsityAthletic, 'VarsityAthleticWeather');
export const VarsityAthleticCountdown = lazyWidget<ThemeWidgetProps>(loadThemesVarsityAthletic, 'VarsityAthleticCountdown');
export const VarsityAthleticAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesVarsityAthletic, 'VarsityAthleticAnnouncement');
export const VarsityAthleticCalendar = lazyWidget<ThemeWidgetProps>(loadThemesVarsityAthletic, 'VarsityAthleticCalendar');
export const VarsityAthleticStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesVarsityAthletic, 'VarsityAthleticStaffSpotlight');
export const VarsityAthleticImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesVarsityAthletic, 'VarsityAthleticImageCarousel');
export const VarsityAthleticTicker = lazyWidget<ThemeWidgetProps>(loadThemesVarsityAthletic, 'VarsityAthleticTicker');

const loadThemesSeniorCountdown = () => import('./themes/senior-countdown');
export const SeniorCountdownLogo = lazyWidget<ThemeWidgetProps>(loadThemesSeniorCountdown, 'SeniorCountdownLogo');
export const SeniorCountdownText = lazyWidget<ThemeWidgetProps>(loadThemesSeniorCountdown, 'SeniorCountdownText');
export const SeniorCountdownClock = lazyWidget<ThemeWidgetProps>(loadThemesSeniorCountdown, 'SeniorCountdownClock');
export const SeniorCountdownWeather = lazyWidget<ThemeWidgetProps>(loadThemesSeniorCountdown, 'SeniorCountdownWeather');
export const SeniorCountdownCountdown = lazyWidget<ThemeWidgetProps>(loadThemesSeniorCountdown, 'SeniorCountdownCountdown');
export const SeniorCountdownAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesSeniorCountdown, 'SeniorCountdownAnnouncement');
export const SeniorCountdownCalendar = lazyWidget<ThemeWidgetProps>(loadThemesSeniorCountdown, 'SeniorCountdownCalendar');
export const SeniorCountdownStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesSeniorCountdown, 'SeniorCountdownStaffSpotlight');
export const SeniorCountdownImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesSeniorCountdown, 'SeniorCountdownImageCarousel');
export const SeniorCountdownTicker = lazyWidget<ThemeWidgetProps>(loadThemesSeniorCountdown, 'SeniorCountdownTicker');

const loadThemesNewsStudioPro = () => import('./themes/news-studio-pro');
export const NewsStudioProLogo = lazyWidget<ThemeWidgetProps>(loadThemesNewsStudioPro, 'NewsStudioProLogo');
export const NewsStudioProText = lazyWidget<ThemeWidgetProps>(loadThemesNewsStudioPro, 'NewsStudioProText');
export const NewsStudioProClock = lazyWidget<ThemeWidgetProps>(loadThemesNewsStudioPro, 'NewsStudioProClock');
export const NewsStudioProWeather = lazyWidget<ThemeWidgetProps>(loadThemesNewsStudioPro, 'NewsStudioProWeather');
export const NewsStudioProCountdown = lazyWidget<ThemeWidgetProps>(loadThemesNewsStudioPro, 'NewsStudioProCountdown');
export const NewsStudioProAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesNewsStudioPro, 'NewsStudioProAnnouncement');
export const NewsStudioProCalendar = lazyWidget<ThemeWidgetProps>(loadThemesNewsStudioPro, 'NewsStudioProCalendar');
export const NewsStudioProStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesNewsStudioPro, 'NewsStudioProStaffSpotlight');
export const NewsStudioProImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesNewsStudioPro, 'NewsStudioProImageCarousel');
export const NewsStudioProTicker = lazyWidget<ThemeWidgetProps>(loadThemesNewsStudioPro, 'NewsStudioProTicker');

const loadThemesCampusQuad = () => import('./themes/campus-quad');
export const CampusQuadLogo = lazyWidget<ThemeWidgetProps>(loadThemesCampusQuad, 'CampusQuadLogo');
export const CampusQuadText = lazyWidget<ThemeWidgetProps>(loadThemesCampusQuad, 'CampusQuadText');
export const CampusQuadClock = lazyWidget<ThemeWidgetProps>(loadThemesCampusQuad, 'CampusQuadClock');
export const CampusQuadWeather = lazyWidget<ThemeWidgetProps>(loadThemesCampusQuad, 'CampusQuadWeather');
export const CampusQuadCountdown = lazyWidget<ThemeWidgetProps>(loadThemesCampusQuad, 'CampusQuadCountdown');
export const CampusQuadAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesCampusQuad, 'CampusQuadAnnouncement');
export const CampusQuadCalendar = lazyWidget<ThemeWidgetProps>(loadThemesCampusQuad, 'CampusQuadCalendar');
export const CampusQuadStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesCampusQuad, 'CampusQuadStaffSpotlight');
export const CampusQuadImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesCampusQuad, 'CampusQuadImageCarousel');
export const CampusQuadTicker = lazyWidget<ThemeWidgetProps>(loadThemesCampusQuad, 'CampusQuadTicker');

const loadThemesAchievementHall = () => import('./themes/achievement-hall');
export const AchievementHallLogo = lazyWidget<ThemeWidgetProps>(loadThemesAchievementHall, 'AchievementHallLogo');
export const AchievementHallText = lazyWidget<ThemeWidgetProps>(loadThemesAchievementHall, 'AchievementHallText');
export const AchievementHallClock = lazyWidget<ThemeWidgetProps>(loadThemesAchievementHall, 'AchievementHallClock');
export const AchievementHallWeather = lazyWidget<ThemeWidgetProps>(loadThemesAchievementHall, 'AchievementHallWeather');
export const AchievementHallCountdown = lazyWidget<ThemeWidgetProps>(loadThemesAchievementHall, 'AchievementHallCountdown');
export const AchievementHallAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesAchievementHall, 'AchievementHallAnnouncement');
export const AchievementHallCalendar = lazyWidget<ThemeWidgetProps>(loadThemesAchievementHall, 'AchievementHallCalendar');
export const AchievementHallStaffSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesAchievementHall, 'AchievementHallStaffSpotlight');
export const AchievementHallImageCarousel = lazyWidget<ThemeWidgetProps>(loadThemesAchievementHall, 'AchievementHallImageCarousel');
export const AchievementHallTicker = lazyWidget<ThemeWidgetProps>(loadThemesAchievementHall, 'AchievementHallTicker');

// ════════════════════════════════════════════════════════════════════════
// Picker-only families (P1-1) — imported by variants-register.ts for the
// builder's variant tiles. Same proxies, same reason: before this these were
// STATIC imports, so every route that pulls the variant catalog compiled the
// whole themed-widget set into its own chunk.
// ════════════════════════════════════════════════════════════════════════

const loadVariantTilesBasicContentTiles = () => import('./variant-tiles/basic-content-tiles');
export const VideoBasicTile = lazyWidget<ThemeWidgetProps>(loadVariantTilesBasicContentTiles, 'VideoBasicTile');
export const VideoCarouselTile = lazyWidget<ThemeWidgetProps>(loadVariantTilesBasicContentTiles, 'VideoCarouselTile');
export const WebpageTile = lazyWidget<ThemeWidgetProps>(loadVariantTilesBasicContentTiles, 'WebpageTile');
export const ImageBasicTile = lazyWidget<ThemeWidgetProps>(loadVariantTilesBasicContentTiles, 'ImageBasicTile');
export const ImageCarouselBasicTile = lazyWidget<ThemeWidgetProps>(loadVariantTilesBasicContentTiles, 'ImageCarouselBasicTile');
export const ExternalHtmlTile = lazyWidget<ThemeWidgetProps>(loadVariantTilesBasicContentTiles, 'ExternalHtmlTile');

// 2026-05-25 monetize-audit — the one ad-network we can integrate
// without partnership sign-off. Drops a rotating sponsor banner that
// reads from the operator's own asset library. Sponsor disclosure
// label baked in for FTC native-advertising compliance.
const loadVariantTilesMonetizeMusicTiles = () => import('./variant-tiles/monetize-music-tiles');
export const HouseAdsBannerTile = lazyWidget<ThemeWidgetProps>(loadVariantTilesMonetizeMusicTiles, 'HouseAdsBannerTile');
export const MusicPlayerTile = lazyWidget<ThemeWidgetProps>(loadVariantTilesMonetizeMusicTiles, 'MusicPlayerTile');

const loadThemesModern2026 = () => import('./themes/modern-2026');
export const ClockGradientDigital = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'ClockGradientDigital');
export const ClockDarkPill = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'ClockDarkPill');
export const ClockMinimalAnalog = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'ClockMinimalAnalog');
export const ClockStackedCard = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'ClockStackedCard');
export const TextBigBold = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'TextBigBold');
export const TextGradient = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'TextGradient');
export const TextHighlight = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'TextHighlight');
export const TextOutlined = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'TextOutlined');
export const AnnouncementModernCard = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'AnnouncementModernCard');
export const AnnouncementSpotlight = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'AnnouncementSpotlight');
export const AnnouncementGlass = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'AnnouncementGlass');
export const TickerLed = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'TickerLed');
export const TickerPastel = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'TickerPastel');
export const TickerAlert = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'TickerAlert');
export const StaffModernCard = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'StaffModernCard');
export const StaffHero = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'StaffHero');
export const CountdownBigNumber = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'CountdownBigNumber');
export const CountdownBlocks = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'CountdownBlocks');
export const CalendarModernList = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'CalendarModernList');
export const WeatherHero = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'WeatherHero');
export const WeatherGlass = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'WeatherGlass');
export const LogoCircle = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'LogoCircle');
export const LogoWordmark = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'LogoWordmark');
export const GalleryModern = lazyWidget<ThemeWidgetProps>(loadThemesModern2026, 'GalleryModern');

const loadThemesLobbyWelcome = () => import('./themes/lobby-welcome');
export const LobbyWelcomeLogo = lazyWidget<ThemeWidgetProps>(loadThemesLobbyWelcome, 'LobbyWelcomeLogo');
export const LobbyWelcomeText = lazyWidget<ThemeWidgetProps>(loadThemesLobbyWelcome, 'LobbyWelcomeText');
export const LobbyWelcomeClock = lazyWidget<ThemeWidgetProps>(loadThemesLobbyWelcome, 'LobbyWelcomeClock');
export const LobbyWelcomeWeather = lazyWidget<ThemeWidgetProps>(loadThemesLobbyWelcome, 'LobbyWelcomeWeather');
export const LobbyWelcomeAnnouncement = lazyWidget<ThemeWidgetProps>(loadThemesLobbyWelcome, 'LobbyWelcomeAnnouncement');
export const LobbyWelcomeCalendar = lazyWidget<ThemeWidgetProps>(loadThemesLobbyWelcome, 'LobbyWelcomeCalendar');
export const LobbyWelcomeTicker = lazyWidget<ThemeWidgetProps>(loadThemesLobbyWelcome, 'LobbyWelcomeTicker');

// 2026-05-19 — the REAL board, one drop. Operator wanted the actual
// pushed scoreboard available as a template, not the generic 7-zone
// primitive layout. This is a faithful BoardScene reproduction that
// reads live game state from the GameStateProvider.
const loadSportsMainScoreboardWidget = () => import('./sports/MainScoreboardWidget');
export const MainScoreboardWidget = lazyWidget<ThemeWidgetProps>(loadSportsMainScoreboardWidget, 'MainScoreboardWidget');

// 2026-05-26 — CTS-fed ribbon scoreboard. Live game state flows from
// the CtsBridge (Beelink mini PC reading the CTS console via Web
// Serial) → API → signed WS → window CustomEvent → this widget.
// Designed for a 480×208 px ribbon panel; transform:scale lets it
// resize for any LED canvas the operator drops it on. See
// packages/scoreboard-cts/README.md for the protocol details.
const loadSportsCtsScoreboard = () => import('./sports/CtsScoreboard');
export const CtsScoreboard = lazyWidget<ThemeWidgetProps>(loadSportsCtsScoreboard, 'CtsScoreboard');

// ────────────────────────────────────────────────────────────────────
// 2026-05-26 — Composable CTS ribbon widget set. Sibling of the all-
// in-one CtsScoreboard above. Each tile is a single zone an operator
// drops onto a custom-canvas ribbon to compose their own layout
// (clock here, score there, sponsor middle, announcements right).
// Every widget shares one window-CustomEvent subscriber, so they all
// stay in sync across the ribbon with zero per-widget round trips.
// All gated to the SPORTS vertical so non-sports tenants never see
// them in the palette.
// ────────────────────────────────────────────────────────────────────
const loadSportsCtsRibbonWidgets = () => import('./sports/CtsRibbonWidgets');
export const CtsClockWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsClockWidget');
export const CtsScoreCombinedWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsScoreCombinedWidget');
export const CtsScoreHomeWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsScoreHomeWidget');
export const CtsScoreAwayWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsScoreAwayWidget');
export const CtsPeriodWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsPeriodWidget');
export const CtsExclusionWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsExclusionWidget');
export const CtsShotClockWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsShotClockWidget');
export const CtsHornFlashWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsHornFlashWidget');
export const CtsSponsorRotatorWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsSponsorRotatorWidget');
export const CtsAnnouncementWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsAnnouncementWidget');
export const CtsCelebrationWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsCelebrationWidget');
export const CtsCelebrationOrchestratorWidget = lazyWidget<ThemeWidgetProps>(loadSportsCtsRibbonWidgets, 'CtsCelebrationOrchestratorWidget');

// ════════════════════════════════════════════════════════════════════
// 2026-05-19 — Composable scoreboard ELEMENT widgets. Operator: "make
// sure everything in these scoreboards are added as widgets and can be
// added or removed." Each is an individual element (team name, logo,
// timeouts, possession, play/shot clock, down&distance, base diamond,
// penalty box, sets, riding time, leaderboard, …) the operator drops,
// positions, sizes, brands, and removes independently. All register
// under the SCOREBOARD canonical type (variant-dispatched) so they
// share the picker's Scoreboard chip; SPORTS-scoped + SPORTS category.
// ════════════════════════════════════════════════════════════════════
const loadSportsSportElementWidgets = () => import('./sports/SportElementWidgets');
export const TeamNameWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'TeamNameWidget');
export const TeamAbbrWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'TeamAbbrWidget');
export const TeamLogoWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'TeamLogoWidget');
export const TeamRecordWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'TeamRecordWidget');
export const GameStatusWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'GameStatusWidget');
export const TimeoutsWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'TimeoutsWidget');
export const PossessionArrowWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'PossessionArrowWidget');
export const PossessionBallWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'PossessionBallWidget');
export const PlayClockWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'PlayClockWidget');
export const ShotClockWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'ShotClockWidget');
export const AddedTimeWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'AddedTimeWidget');
export const BonusLampWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'BonusLampWidget');
export const SponsorSlotWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'SponsorSlotWidget');
export const TeamFoulsWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgets, 'TeamFoulsWidget');

const loadSportsSportElementWidgetsSports = () => import('./sports/SportElementWidgets.sports');
export const DownDistanceWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'DownDistanceWidget');
export const BallOnWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'BallOnWidget');
export const FlagIndicatorWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'FlagIndicatorWidget');
export const CountWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'CountWidget');
export const BaseDiamondWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'BaseDiamondWidget');
export const InningHalfWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'InningHalfWidget');
export const PitchCountWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'PitchCountWidget');
export const PitchSpeedWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'PitchSpeedWidget');
export const PenaltyBoxWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'PenaltyBoxWidget');
export const PowerPlayBadgeWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'PowerPlayBadgeWidget');
export const SetScoresWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'SetScoresWidget');
export const ServeIndicatorWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'ServeIndicatorWidget');
export const RidingTimeWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'RidingTimeWidget');
export const WeightClassWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'WeightClassWidget');
export const TeamScoreRunningWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'TeamScoreRunningWidget');
export const LeaderboardWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'LeaderboardWidget');
export const CardCountWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'CardCountWidget');
export const StatPairWidget = lazyWidget<ThemeWidgetProps>(loadSportsSportElementWidgetsSports, 'StatPairWidget');

// 2026-05-19 — live RIBBON-board + SCOREBUG composite widgets (the
// surfaces the operator said were missing entirely). One-drop, live-
// bound, resize for any ribbon chain / OBS overlay.
const loadSportsRibbonScorebugWidgets = () => import('./sports/RibbonScorebugWidgets');
export const RibbonScoreboardWidget = lazyWidget<ThemeWidgetProps>(loadSportsRibbonScorebugWidgets, 'RibbonScoreboardWidget');
export const ScorebugWidget = lazyWidget<ThemeWidgetProps>(loadSportsRibbonScorebugWidgets, 'ScorebugWidget');


// ════════════════════════════════════════════════════════════════════════
// TEST SUPPORT — `warmAllWidgetFamilies()`
//
// Every export above renders `null` until its chunk resolves, which is the
// right behaviour on a screen and the wrong one for a jsdom unit test that
// renders a widget and asserts on its DOM in the same synchronous tick. Such
// a test must not be left to "pass" against an empty container — that is a
// false green, not a passing test.
//
// So the widget suites await this once in `beforeAll`: it resolves every
// family chunk up front, after which the proxies render their real component
// on FIRST render, exactly as they do on a warmed screen. The test still goes
// through the real proxy — nothing is stubbed.
//
// ⚠ Never call this from application code. Loading all 169 families is exactly
// the cost this wave removed.
// ════════════════════════════════════════════════════════════════════════
export const ALL_WIDGET_FAMILY_LOADERS: readonly WidgetChunkLoader[] = [
  loadThemesGymPe,
  loadThemesPrincipalsOffice,
  loadThemesOfficeDashboard,
  loadThemesBackToSchool,
  loadThemesBusLoop,
  loadThemesDinerChalkboard,
  loadThemesFinalChance,
  loadThemesHighSchoolAthletics,
  loadThemesLibraryQuiet,
  loadThemesMiddleSchoolHall,
  loadThemesMusicArts,
  loadThemesStemScience,
  loadThemesSunshineAcademy,
  loadThemesRainbowRibbon,
  loadThemesRainbowAnimated,
  loadThemesFieldDay,
  loadThemesBulletinBoard,
  loadThemesStorybook,
  loadThemesTrackDay,
  loadThemesScorebug,
  loadThemesJumbotronPro,
  loadThemesGenericWidgets,
  loadAnimatedWelcomeWidget,
  loadAnimatedWelcomePortraitWidget,
  loadSportsSportWidgets,
  loadSportsSwimDiveWidgets,
  loadSportsStadiumMeetBoardWidget,
  loadFitnessFitnessMusicPlayerWidget,
  loadFitnessFitnessLiveTVWidget,
  loadFitnessFitnessAdBannerWidget,
  loadFitnessFitnessClassScheduleWidget,
  loadFitnessFitnessTrainingVideoWidget,
  loadStreamingWidget,
  loadHouseAdsBannerWidget,
  loadMusicPlayerWidget,
  loadFitnessFitnessWorkoutTimerWidget,
  loadFitnessFitnessMotivationalQuoteWidget,
  loadFitnessFitnessAppLibraryWidget,
  loadFitnessFitnessStadiumWidget,
  loadFitnessFitnessIronWidget,
  loadFitnessFitnessMarqueeWidget,
  loadFitnessFitnessChannelGuideWidget,
  loadFitnessFitnessDiscothequeWidget,
  loadFitnessFitnessLockerWidget,
  loadFitnessFitnessSplashWidget,
  loadFitnessFitnessTelemetryWidget,
  loadFitnessFitnessCragWidget,
  loadFitnessFitnessCornermanWidget,
  loadFitnessFitnessRecessWidget,
  loadFitnessFitnessReformerWidget,
  loadFitnessFitnessTrailheadWidget,
  loadFitnessFitnessVaultWidget,
  loadFitnessFitnessLobbyWidget,
  loadFitnessFitnessStickLauncherWidget,
  loadRestaurantMenuBoardWidget,
  loadRestaurantComboCarouselWidget,
  loadRestaurantWaitTimeWidget,
  loadRestaurantLoyaltyTickerWidget,
  loadRestaurantSpecialsCalloutWidget,
  loadRestaurantAllergyLegendWidget,
  loadBarTapListWidget,
  loadBarCocktailMenuWidget,
  loadBarHappyHourCountdownWidget,
  loadBarGameDayScheduleWidget,
  loadBarEventTonightWidget,
  loadBarTriviaScoreboardWidget,
  loadRetailRetailProductGridWidget,
  loadRetailRetailPriceCalloutWidget,
  loadRetailRetailSaleCountdownWidget,
  loadRetailRetailWayfindingMapWidget,
  loadRetailRetailLoyaltyQRWidget,
  loadRetailRetailLookbookCarouselWidget,
  loadRetailRetailStorefrontHoursWidget,
  loadAnimatedWelcomeMiddleWidget,
  loadAnimatedWelcomeHighWidget,
  loadAnimatedCafeteriaElementaryWidget,
  loadAnimatedBackgroundWidget,
  loadHsHsVarsityWidget,
  loadHsHsBroadcastWidget,
  loadHsHsYearbookWidget,
  loadHsHsTerminalWidget,
  loadHsHsTransitWidget,
  loadHsHsGalleryWidget,
  loadHsHsBlueprintWidget,
  loadHsHsZineWidget,
  loadMsMsArcadeWidget,
  loadMsMsAtlasWidget,
  loadMsMsFieldnotesWidget,
  loadMsMsGreenhouseWidget,
  loadMsMsHomeroomWidget,
  loadMsMsPaperWidget,
  loadMsMsPlaylistWidget,
  loadMsMsStudioWidget,
  loadMsMsArcadePortraitWidget,
  loadMsMsAtlasPortraitWidget,
  loadMsMsFieldnotesPortraitWidget,
  loadMsMsGreenhousePortraitWidget,
  loadMsMsHomeroomPortraitWidget,
  loadMsMsPaperPortraitWidget,
  loadMsMsPlaylistPortraitWidget,
  loadMsMsStudioPortraitWidget,
  loadAnimatedCafeteriaMiddleWidget,
  loadAnimatedCafeteriaHighWidget,
  loadAnimatedBusBoardWidget,
  loadAnimatedMainEntranceWidget,
  loadAnimatedHallwayScheduleWidget,
  loadAnimatedBellScheduleWidget,
  loadAnimatedMorningNewsWidget,
  loadAnimatedAchievementShowcaseWidget,
  loadScrapbookHallwayWidget,
  loadAnimatedHallwaySchedulePortraitWidget,
  loadAnimatedBellSchedulePortraitWidget,
  loadAnimatedCafeteriaFoodtruckPortraitWidget,
  loadAnimatedBusBoardPortraitWidget,
  loadAnimatedMainEntrancePortraitWidget,
  loadAnimatedMorningNewsPortraitWidget,
  loadAnimatedAchievementShowcasePortraitWidget,
  loadAnimatedCafeteriaElementaryPortraitWidget,
  loadAnimatedWelcomeHighPortraitWidget,
  loadHsHsBlueprintPortraitWidget,
  loadHsHsVarsityPortraitWidget,
  loadAnimatedWelcomeMiddlePortraitWidget,
  loadAnimatedCafeteriaMiddlePortraitWidget,
  loadHsHsBroadcastPortraitWidget,
  loadHsHsGalleryPortraitWidget,
  loadHsHsTerminalPortraitWidget,
  loadHsHsTransitPortraitWidget,
  loadHsHsYearbookPortraitWidget,
  loadHsHsZinePortraitWidget,
  loadBulletinCafeteriaPortraitWidget,
  loadBulletinHallwayPortraitWidget,
  loadAnimatedCafeteriaHighPortraitWidget,
  loadAnimatedCafeteriaChalkboardPortraitWidget,
  loadScrapbookCafeteriaPortraitWidget,
  loadScrapbookHallwayPortraitWidget,
  loadStorybookCafeteriaPortraitWidget,
  loadStorybookHallwayPortraitWidget,
  loadDecorationWidget,
  loadShapeWidget,
  loadIconWidget,
  loadHolidayWidget,
  loadScrapbookCafeteriaWidget,
  loadStorybookHallwayWidget,
  loadBulletinHallwayWidget,
  loadStorybookCafeteriaWidget,
  loadBulletinCafeteriaWidget,
  loadAnimatedCafeteriaChalkboardWidget,
  loadAnimatedCafeteriaFoodtruckWidget,
  loadThemesScrapbook,
  loadThemesLockerHallway,
  loadThemesSpiritRally,
  loadThemesStemLab,
  loadThemesMorningNews,
  loadThemesArtStudio,
  loadThemesVarsityAthletic,
  loadThemesSeniorCountdown,
  loadThemesNewsStudioPro,
  loadThemesCampusQuad,
  loadThemesAchievementHall,
  loadVariantTilesBasicContentTiles,
  loadVariantTilesMonetizeMusicTiles,
  loadThemesModern2026,
  loadThemesLobbyWelcome,
  loadSportsMainScoreboardWidget,
  loadSportsCtsScoreboard,
  loadSportsCtsRibbonWidgets,
  loadSportsSportElementWidgets,
  loadSportsSportElementWidgetsSports,
  loadSportsRibbonScorebugWidgets,
];

export function warmAllWidgetFamilies(): Promise<unknown> {
  return Promise.all(ALL_WIDGET_FAMILY_LOADERS.map((l) => loadWidgetChunk(l)));
}
