-- 2026-09-21 — Screen.lastBundleId: the identity the player actually reloads on.
--
-- WHY. Since the 2026-09-02 efficiency work the player decides whether to
-- reload by comparing `bundleId` — a hash of the CLIENT-BUNDLE build inputs
-- (apps/web/scripts/build-info.cjs) — not the git commit SHA. That is correct:
-- an API-only, docs, APK or test commit cannot change what the browser
-- downloads, so it reloads nobody. But the player kept REPORTING only its SHA
-- (`last_bundle_sha`) and the dashboard kept GRADING on SHA equality, so every
-- such deploy moved the deployed SHA out from under a fleet that correctly did
-- not reload — and every online screen read "on an older build" forever. "App
-- current 5/18" on a healthy fleet, with a Resync that could never clear it.
-- This column lets both sides compare the same identity the reload is made on.
--
-- ADDITIVE AND NON-DESTRUCTIVE:
--   * ONE NULLABLE column, TEXT, no default — a catalogue-only change in
--     Postgres, instant at any row count, no table rewrite and no backfill.
--     Every existing screen reads NULL, which the dashboard treats as "this
--     build does not report one" and falls back to the SHA comparison it uses
--     today — i.e. today's exact behaviour until players start reporting.
--   * no index (the column is read per-row off the fleet list, never filtered
--     or joined on), no constraint, nothing dropped, renamed or rewritten.
--
-- `lock_timeout`: ALTER TABLE takes a brief ACCESS EXCLUSIVE lock on "screens",
-- the table every manifest poll, heartbeat and register reads. If a long
-- transaction holds it, a lock request that WAITS queues the whole fleet behind
-- it. Five seconds, then fail — railway-start retries, and a failed migrate
-- never goes healthy, so Railway keeps the previous deployment serving. Failing
-- loudly beats stalling the fleet.
--
-- IDEMPOTENT (`IF NOT EXISTS`) because this repo's dev flow is `pnpm db:push`:
-- a database that already took this shape applies the file as a no-op instead
-- of failing on "column already exists".
--
-- DDL generated by Prisma (`migrate diff --from-schema-datamodel …
-- --to-schema-datamodel … --script`) so it cannot drift from the client:
--   ALTER TABLE "screens" ADD COLUMN "last_bundle_id" TEXT;

SET lock_timeout = '5s';

ALTER TABLE "screens"
  ADD COLUMN IF NOT EXISTS "last_bundle_id" TEXT;
