/**
 * gen-font-manifest — regenerate fonts/manifest.json from the Designer prompt.
 *
 *   pnpm --filter renderer gen:fonts
 *
 * Reads DESIGNER_FONTS out of apps/api/src/ai/designer-prompt.ts, adds the
 * look-alike targets in SUBSTITUTES, and maps every family to the fontsource
 * package that ships it (the variable build when one exists). It does NOT
 * install anything: a family whose package is missing from package.json fails
 * the run with the exact `pnpm add` to make — the manifest can never name a
 * font the image does not carry.
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { packageRoot } from '../paths.js';
import { SUBSTITUTES, extractDesignerFonts, fontsourceId, manifestPath, type FontManifest } from '../fonts/manifest.js';

const PROMPT_REL = 'apps/api/src/ai/designer-prompt.ts';

function main(): number {
  const root = packageRoot();
  const repoRoot = path.resolve(root, '..', '..');
  const promptFile = path.join(repoRoot, PROMPT_REL);
  const designerFonts = extractDesignerFonts(fs.readFileSync(promptFile, 'utf8'));
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')) as {
    dependencies?: Record<string, string>;
  };
  const deps = pkg.dependencies ?? {};
  const req = createRequire(path.join(root, 'package.json'));

  const wanted = [...new Set([...designerFonts, ...Object.values(SUBSTITUTES)])];
  const families: Record<string, string> = {};
  const problems: string[] = [];
  for (const family of wanted) {
    const id = fontsourceId(family);
    const candidates = [`@fontsource-variable/${id}`, `@fontsource/${id}`];
    const chosen = candidates.find((name) => deps[name]);
    if (!chosen) {
      problems.push(
        `${family}: no fontsource package in apps/renderer/package.json — ` +
          `pnpm --filter renderer add ${candidates[0]}@5.3.0  (or ${candidates[1]} if there is no variable build)`,
      );
      continue;
    }
    try {
      const meta = JSON.parse(fs.readFileSync(req.resolve(`${chosen}/metadata.json`), 'utf8')) as { family?: string };
      if ((meta.family ?? '').toLowerCase() !== family.toLowerCase()) {
        problems.push(`${family}: ${chosen} ships "${meta.family}", not "${family}"`);
        continue;
      }
    } catch (e) {
      problems.push(`${family}: ${chosen} is listed but not installed (${(e as Error).message}) — run pnpm install`);
      continue;
    }
    families[family] = chosen;
  }
  if (problems.length > 0) {
    process.stderr.write(`gen-font-manifest: ${problems.length} problem(s):\n  ${problems.join('\n  ')}\n`);
    return 1;
  }

  const manifest: FontManifest & { $comment: string } = {
    $comment:
      'GENERATED by `pnpm --filter renderer gen:fonts` (src/tools/gen-font-manifest.ts). Do not hand-edit: ' +
      'designerFonts mirrors DESIGNER_FONTS in apps/api/src/ai/designer-prompt.ts, substitutes is SUBSTITUTES in src/fonts/manifest.ts.',
    generatedFrom: `${PROMPT_REL}#DESIGNER_FONTS`,
    designerFonts,
    substitutes: { ...SUBSTITUTES },
    families,
  };
  const out = manifestPath();
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, JSON.stringify(manifest, null, 2) + '\n');
  process.stdout.write(`gen-font-manifest: wrote ${path.relative(repoRoot, out)} — ${Object.keys(families).length} families\n`);
  return 0;
}

process.exitCode = main();
