-- 2026-09-22 — AI usage ledger + live model catalog state.
--
-- WHY. Greg (2026-09-22): customers should get only so much AI included with the $25/screen/month
-- plan, models should upgrade themselves as vendors ship them, and a cheaper model should
-- automatically mean more usage for the same money. That needs two things the database did not
-- have:
--   * ai_usage_events — one row per provider call: tokens and the dollar cost at the catalog price
--     of the model that served it. The monthly included allowance is the SUM of an organisation's
--     platform-key rows, so a cheaper model stretches it on the day it is adopted. Append-only.
--   * ai_catalog_state — ONE row holding the catalog's editable state (models learned by the daily
--     sync, price moves, tier families, super-admin pins). Missing row = the in-code seed.
--
-- ADDITIVE AND NON-DESTRUCTIVE: two NEW tables, two indexes, one foreign key. Nothing existing is
-- altered, so no lock is taken on any hot table (tenants is only REFERENCED by the new FK; adding
-- a foreign key takes SHARE ROW EXCLUSIVE on the referenced table, which does not block reads —
-- lock_timeout keeps even that from queueing behind a long transaction).
--
-- IDEMPOTENT because the dev flow is `pnpm db:push`: IF NOT EXISTS on every table and index, and
-- the foreign key behind a pg_constraint guard, so a database that already took this shape applies
-- the file as a no-op.
--
-- DDL generated by Prisma (`migrate diff --from-schema-datamodel … --to-schema-datamodel …
-- --script`) and then made idempotent — the column list is unchanged from its output.

SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS "ai_usage_events" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "org_tenant_id" TEXT NOT NULL,
    "feature" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "input_tokens" INTEGER NOT NULL DEFAULT 0,
    "output_tokens" INTEGER NOT NULL DEFAULT 0,
    "cache_read_tokens" INTEGER NOT NULL DEFAULT 0,
    "cache_write_tokens" INTEGER NOT NULL DEFAULT 0,
    "cost_micros" INTEGER NOT NULL,
    "duration_ms" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_usage_events_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ai_catalog_state" (
    "id" TEXT NOT NULL,
    "state" JSONB NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_catalog_state_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ai_usage_events_org_tenant_id_source_created_at_idx"
  ON "ai_usage_events"("org_tenant_id", "source", "created_at");

CREATE INDEX IF NOT EXISTS "ai_usage_events_tenant_id_created_at_idx"
  ON "ai_usage_events"("tenant_id", "created_at");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ai_usage_events_tenant_id_fkey'
  ) THEN
    ALTER TABLE "ai_usage_events"
      ADD CONSTRAINT "ai_usage_events_tenant_id_fkey"
      FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
