import { Controller, Post, Body, HttpException, HttpStatus } from '@nestjs/common';
import * as jwt from 'jsonwebtoken';
import { PrismaService } from '../prisma/prisma.service';
import { requireSecret } from '../security/required-secret';

/**
 * Device-side endpoints — called by the Android player APK without admin
 * auth. Proof of identity is the pairing code (already generated by
 * /screens/register and claimed by an admin via /screens/pair) plus the
 * device fingerprint.
 */
@Controller('api/v1/devices')
export class DevicesController {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * The Android APK posts the pairing code the operator typed on screen.
   * If the code matches a Screen that an admin has already claimed, we
   * mint a long-lived device JWT and (when the tenant has USB ingest
   * enabled) include the HMAC key in the same response so the player can
   * verify USB bundles offline without a separate fetch.
   */
  @Post('pair')
  async pair(
    @Body() body: {
      code?: string;
      deviceFingerprint?: string;
      model?: string;
      os?: string;
      appVersion?: string;
    },
  ) {
    const code = body.code?.trim().toUpperCase();
    const fp = body.deviceFingerprint?.trim();
    if (!code) throw new HttpException('code is required', HttpStatus.BAD_REQUEST);

    const screen = await this.prisma.client.screen.findUnique({
      where: { pairingCode: code },
      include: {
        tenant: {
          select: {
            id: true, slug: true, name: true,
            usbIngestEnabled: true, usbIngestKey: true,
          },
        },
      },
    });

    // sec-fix(wave1) #6: the deviceFingerprint-only fallback path (used
    // to silently re-pair an already-paired screen after a reinstall) has
    // been removed. An attacker who can guess/recover a device
    // fingerprint could otherwise mint a fresh 365-day device JWT for
    // any screen in the fleet — effectively a takeover of the kiosk
    // without ever going through an admin. Going forward, every re-pair
    // requires a fresh pairing code. Document this in operator
    // onboarding notes: "Reinstalling the player? Ask an admin for a
    // new pairing code."
    const target = screen;

    if (!target) {
      throw new HttpException('Invalid or expired pairing code', HttpStatus.NOT_FOUND);
    }
    if (!target.tenantId || !target.tenant) {
      throw new HttpException('This screen has not been claimed by an admin yet', HttpStatus.PRECONDITION_REQUIRED);
    }

    // Bind / refresh device-side metadata. Idempotent — re-pairs are fine.
    await this.prisma.client.screen.update({
      where: { id: target.id },
      data: {
        deviceFingerprint: fp || target.deviceFingerprint,
        osInfo: body.os || target.osInfo,
        userAgent: `${body.model || ''} ${body.appVersion || ''}`.trim() || target.userAgent,
        status: 'ONLINE',
        pairedAt: target.pairedAt || new Date(),
      },
    });

    const token = jwt.sign(
      { sub: target.id, tenantId: target.tenantId, kind: 'device', fp },
      // sec-fix(wave1) #2: fail at boot in prod rather than sign with a default.
      requireSecret('DEVICE_JWT_SECRET', { devFallback: 'dev_only_device_jwt_secret_CHANGE_ME' }),
      { expiresIn: '365d' }, // 1-year — kiosks shouldn't re-pair often
    );

    const usb = target.tenant.usbIngestEnabled
      ? {
          usbIngestEnabled: true,
          usbIngestKey: target.tenant.usbIngestKey || null,
        }
      : { usbIngestEnabled: false };

    return {
      token,
      screenId: target.id,
      tenantId: target.tenantId,
      tenantSlug: target.tenant.slug,
      tenantName: target.tenant.name,
      ...usb,
    };
  }
}
