-- 2026-09-23 — AI board history: which template the operator kept from a generated batch.
--
-- WHY. A batch of three AI boards used to live only in the browser until the operator kept one;
-- the other two were thrown away with the tokens that paid for them. With generation moved into
-- `ai_designer_jobs`, every batch's full result is already a row. Greg (2026-09-23): "keep a
-- history of the generated templates so we aren't just throwing away tokens, so they can go back
-- to them and decide later if they want to continue tweaking them." DONE jobs are now kept 90 days
-- and listed by `GET /templates/generate-designer/jobs`; `POST /templates/create-designer` stamps
-- the kept template's id on the job its batch came from, and a stamped job is never auto-deleted
-- (retention lives in designer-jobs.service.ts — no cron).
--
-- ADDITIVE AND NON-DESTRUCTIVE: one NULLABLE column with no default (a catalogue-only change in
-- Postgres, instant at any row count — every existing job reads as "nothing kept", which is the
-- truth) and one b-tree index on it. Nothing is dropped, renamed or rewritten. Plain TEXT, not a
-- foreign key to "templates": the history row must not couple the templates table's delete path
-- to this table.
--
-- `lock_timeout`: ADD COLUMN takes a brief ACCESS EXCLUSIVE lock on "ai_designer_jobs" and the
-- index build a SHARE lock; the designer-jobs worker heartbeats this table every 15 s while a job
-- runs. Five seconds, then fail — railway-start retries, and a failed migrate never goes healthy,
-- so Railway keeps the previous deployment serving. The table is young and small, so the plain
-- (non-CONCURRENTLY) index build holds its lock for milliseconds.
--
-- IDEMPOTENT (IF NOT EXISTS on both statements) because this repo's dev flow is `pnpm db:push`: a
-- database that already took this shape applies the file as a no-op.
--
-- DDL generated by Prisma (`migrate diff --from-schema-datamodel <master 6823f580>
-- --to-schema-datamodel <this commit> --script`) and then made idempotent — the column, the index
-- name and its column list are unchanged from its output.

SET lock_timeout = '5s';

ALTER TABLE "ai_designer_jobs" ADD COLUMN IF NOT EXISTS "kept_template_id" TEXT;

CREATE INDEX IF NOT EXISTS "ai_designer_jobs_kept_template_id_idx" ON "ai_designer_jobs"("kept_template_id");
