-- 2026-09-23 — AI Designer background generation jobs (Codex finding 5 + the async gap).
--
-- WHY. `POST /templates/generate-designer/candidates` is one synchronous HTTP request that already
-- runs 1–2 min (three medium-effort draws) and grows to 3–4 min with the render → review → revise
-- pipeline. iOS Safari drops a backgrounded fetch, every deploy kills in-flight requests, and there
-- was no progress, no cancel, no resume, and the Regenerate replay lived only in browser memory. A
-- generation is now a row the dashboard creates and polls; an in-process worker on any replica
-- claims it (FOR UPDATE SKIP LOCKED) and runs the same AiService call the sync endpoint makes.
-- `request` is the persisted, versioned design request that POST …/jobs/:id/again replays.
--
-- ADDITIVE AND NON-DESTRUCTIVE: one brand-new table, three indexes, one foreign key. Nothing
-- existing is altered, so no lock is taken on any hot table ("tenants" is only REFERENCED by the
-- new FK; adding a foreign key takes SHARE ROW EXCLUSIVE on the referenced table, which does not
-- block reads — lock_timeout keeps even that from queueing behind a long transaction, and a failed
-- migrate never goes healthy, so Railway keeps the previous deployment serving).
--
-- The unique (tenant_id, idempotency_key) index is "unique where not null" by construction: NULLs
-- are distinct in a Postgres unique index, so any number of jobs may carry no key. A PARTIAL index
-- would say the same thing but cannot be declared in schema.prisma on Prisma 5.22, so it would
-- drift from the datamodel on every `migrate diff` / `db:push`.
--
-- IDEMPOTENT because the dev flow is `pnpm db:push`: IF NOT EXISTS on the table and every index,
-- and the foreign key behind a pg_constraint guard, so a database that already took this shape
-- applies the file as a no-op.
--
-- DDL generated by Prisma (`migrate diff --from-schema-datamodel <master> --to-schema-datamodel
-- <this commit> --script`) and then made idempotent — the column list is unchanged from its output.

SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS "ai_designer_jobs" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "user_id" TEXT,
    "status" TEXT NOT NULL DEFAULT 'queued',
    "request" JSONB NOT NULL,
    "progress" JSONB,
    "result" JSONB,
    "error" JSONB,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "lease_owner" TEXT,
    "heartbeat_at" TIMESTAMP(3),
    "idempotency_key" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" TIMESTAMP(3),
    "finished_at" TIMESTAMP(3),

    CONSTRAINT "ai_designer_jobs_pkey" PRIMARY KEY ("id")
);

-- The tenant's own jobs, newest first: status reads, the active-job cap, retention.
CREATE INDEX IF NOT EXISTS "ai_designer_jobs_tenant_id_created_at_idx"
  ON "ai_designer_jobs"("tenant_id", "created_at" DESC);

-- The worker's claim (status = 'queued' ORDER BY created_at) and its stale sweep.
CREATE INDEX IF NOT EXISTS "ai_designer_jobs_status_created_at_idx"
  ON "ai_designer_jobs"("status", "created_at");

-- A retried POST with the same key returns the job it already created.
CREATE UNIQUE INDEX IF NOT EXISTS "ai_designer_jobs_tenant_id_idempotency_key_key"
  ON "ai_designer_jobs"("tenant_id", "idempotency_key");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ai_designer_jobs_tenant_id_fkey'
  ) THEN
    ALTER TABLE "ai_designer_jobs"
      ADD CONSTRAINT "ai_designer_jobs_tenant_id_fkey"
      FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
