-- 2026-09-23 — signage-profile VIDEO TRANSCODE jobs (4K uploads).
--
-- WHY. Direct browser → Supabase uploads now accept videos up to 2 GB, and every screen downloads
-- whatever an asset's file_url points at — a 1.5 GB camera original is 1.5 GB of Supabase egress
-- per screen. After a video upload one row is queued here; VideoTranscodeWorker (every replica,
-- FOR UPDATE SKIP LOCKED) re-encodes it to H.264 High (1080p, or 2160p for a 4K source) and swaps
-- the asset's file_url to the optimized copy ONLY when it is smaller and provably complete.
--
-- ADDITIVE AND NON-DESTRUCTIVE: one brand-new table, four indexes, two foreign keys. Nothing
-- existing is altered. The FKs only REFERENCE "tenants" and "assets": adding a foreign key takes
-- SHARE ROW EXCLUSIVE on the referenced table, which does not block reads, and the new table is
-- empty so validation is instant. lock_timeout keeps even that brief lock from queueing behind a
-- long transaction on "assets" (a failed migrate never goes healthy, so Railway keeps the previous
-- deployment serving and railway-start retries).
--
-- asset_id is NULLABLE + ON DELETE SET NULL on purpose: a job that swapped an asset still owns the
-- retained ORIGINAL object, and the retention sweep must be able to remove it after the asset
-- itself is deleted. The unique index on asset_id is "unique where not null" by construction
-- (NULLs are distinct in a Postgres unique index) — one transcode per live asset.
--
-- IDEMPOTENT because the dev flow is `pnpm db:push`: IF NOT EXISTS on the table and every index,
-- and each foreign key behind a pg_constraint guard, so a database that already took this shape
-- applies the file as a no-op.
--
-- DDL generated by Prisma (`migrate diff --from-schema-datamodel <adfba022> --to-schema-datamodel
-- <this commit> --script`) and then made idempotent — the column list is unchanged from its output.

SET lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS "video_transcode_jobs" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "asset_id" TEXT,
    "status" TEXT NOT NULL DEFAULT 'queued',
    "reason" TEXT,
    "progress" INTEGER,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "lease_owner" TEXT,
    "heartbeat_at" TIMESTAMP(3),
    "source_url" TEXT NOT NULL,
    "source_bytes" INTEGER,
    "output_url" TEXT,
    "output_bytes" INTEGER,
    "details" JSONB,
    "error" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" TIMESTAMP(3),
    "finished_at" TIMESTAMP(3),
    "original_delete_after" TIMESTAMP(3),
    "original_deleted_at" TIMESTAMP(3),
    "original_retained_reason" TEXT,

    CONSTRAINT "video_transcode_jobs_pkey" PRIMARY KEY ("id")
);

-- One transcode per live asset (the enqueue is ON CONFLICT DO NOTHING).
CREATE UNIQUE INDEX IF NOT EXISTS "video_transcode_jobs_asset_id_key"
  ON "video_transcode_jobs"("asset_id");

-- The worker's claim (status = 'queued' ORDER BY created_at) and its stale sweep.
CREATE INDEX IF NOT EXISTS "video_transcode_jobs_status_created_at_idx"
  ON "video_transcode_jobs"("status", "created_at");

-- A tenant's own jobs, newest first.
CREATE INDEX IF NOT EXISTS "video_transcode_jobs_tenant_id_created_at_idx"
  ON "video_transcode_jobs"("tenant_id", "created_at" DESC);

-- The retention sweep (done jobs whose original is due).
CREATE INDEX IF NOT EXISTS "video_transcode_jobs_original_delete_after_idx"
  ON "video_transcode_jobs"("original_delete_after");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'video_transcode_jobs_tenant_id_fkey'
  ) THEN
    ALTER TABLE "video_transcode_jobs"
      ADD CONSTRAINT "video_transcode_jobs_tenant_id_fkey"
      FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'video_transcode_jobs_asset_id_fkey'
  ) THEN
    ALTER TABLE "video_transcode_jobs"
      ADD CONSTRAINT "video_transcode_jobs_asset_id_fkey"
      FOREIGN KEY ("asset_id") REFERENCES "assets"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
