/**
 * Where a template's pre-rendered poster PNG lives.
 *
 * ONE implementation, deliberately. Two surfaces need "what does this board
 * look like?" — the templates gallery card (ScaledTemplateThumbnail) and the
 * Screens page's Expected-content preview — and a second copy of this rule is
 * how one of them ends up showing a different board than the other. Pure and
 * dependency-free so both can import it (and so it is testable without a DOM).
 *
 * The posters themselves are generated by gen-template-posters.cjs into
 * apps/web/public/templates/_thumbs/, and the Poster Freshness CI gate fails
 * the build if a board's HTML changes without its poster being regenerated.
 */

export interface PosterZone {
  widgetType: string;
  defaultConfig?: unknown;
}

/** Bump on every poster regeneration so browsers/CDN refetch the new PNGs.
 *  Date-based; append a letter for multiple regens in one day (…24b). */
export const POSTER_VERSION = '20260826a';

/**
 * For a board preview (a single EXTERNAL_HTML zone), the path to its
 * pre-rendered static poster PNG. An <img> is "just there" — one ~40KB cached
 * image, no document or process — where a live 3840×2160 iframe per tile
 * pegged the main thread.
 *
 * Returns null when there is no single EXTERNAL_HTML board url: a zone-based
 * template renders its widgets instead, and a custom board with no generated
 * poster falls back to the live frame.
 */
export function templatePosterUrl(zones: PosterZone[] | null | undefined, opts?: { allowCustomized?: boolean }): string | null {
  if (!zones || zones.length !== 1) return null;
  const z = zones[0];
  if (z.widgetType !== 'EXTERNAL_HTML') return null;
  let cfg: any = z.defaultConfig;
  if (typeof cfg === 'string') { try { cfg = JSON.parse(cfg); } catch { return null; } }
  // A customized board — operator applied brand / text / image / style
  // overrides — must render LIVE (frozen iframe with ?brand=/?text=/?img=) so
  // those show. The static poster is the pristine default look and would mask
  // the customization (e.g. "Apply brand did nothing" in the gallery).
  //
  // `allowCustomized` exists for callers that CANNOT render a live frame and
  // whose alternative is a blank grey box — a table row, say. There the poster
  // is the honest answer to "which board is this", and the caller is
  // responsible for not implying it reflects the operator's overrides.
  if (!opts?.allowCustomized && cfg && (cfg.brand || cfg.textOverrides || cfg.imageOverrides || cfg._styles)) return null;
  const url: unknown = cfg?.url;
  if (typeof url !== 'string' || !url.startsWith('/templates/')) return null;
  const clean = url.split('?')[0].split('#')[0];
  if (!clean.endsWith('.html')) return null;
  // A board that ships BOTH native compositions is one HTML file; the portrait
  // preset points at `...html?orientation=portrait`. Its poster is captured at
  // 9:16 beside the landscape one as `<name>-portrait.png` — without this the
  // stripped query would resolve a portrait card to the LANDSCAPE poster.
  const isPortrait = /[?&]orientation=portrait\b/.test(url);
  // Cache-bust: poster PNGs live at a stable URL, so a browser (and Vercel's
  // edge) hard-cache the OLD image after we regenerate a board's poster.
  return (
    clean.replace('/templates/', '/templates/_thumbs/').replace(/\.html$/, isPortrait ? '-portrait.png' : '.png') +
    `?v=${POSTER_VERSION}`
  );
}
